const providerApiConsoleUrls: Readonly<Record<string, string>> = {
  openai: "https://platform.openai.com/api-keys",
  elevenlabs: "https://elevenlabs.io/app/settings/api-keys",
  meta: "https://llama.developer.meta.com/",
  anthropic: "https://console.anthropic.com/settings/keys",
  google: "https://aistudio.google.com/app/apikey",
  minimax: "https://platform.minimax.io/user-center/basic-information/interface-key",
  moonshot: "https://platform.moonshot.ai/console/api-keys",
  "kimi-code": "https://www.kimi.com/code/console",
  "qwen-portal": "https://chat.qwen.ai/",
  together: "https://api.together.ai/settings/api-keys",
  huggingface: "https://huggingface.co/settings/tokens",
  synthetic: "https://synthetic.new/settings/api",
  venice: "https://venice.ai/settings/api",
  xiaomi: "https://platform.xiaomimimo.com/",
  azure: "https://portal.azure.com/",
  azure_foundry: "https://ai.azure.com/",
  anthropic_vertex: "https://console.cloud.google.com/apis/credentials",
  google_vertex: "https://console.cloud.google.com/apis/credentials",
  perplexity: "https://www.perplexity.ai/settings/api",
  arcee: "https://app.arcee.ai/",
  nous: "https://portal.nousresearch.com/",
  "cloudflare-ai-gateway": "https://dash.cloudflare.com/",
  groq: "https://console.groq.com/keys",
  openrouter: "https://openrouter.ai/settings/keys",
  opencode_zen: "https://opencode.ai/auth",
  "z.ai": "https://z.ai/manage-apikey/apikey-list",
  "z.ai-coding": "https://z.ai/manage-apikey/apikey-list",
  chutes: "https://chutes.ai/app/settings/api",
  "vercel-ai-gateway": "https://vercel.com/ai-gateway",
  featherless: "https://featherless.ai/account/api-keys",
  longcat: "https://longcat.chat/platform",
  xai: "https://console.x.ai/",
  qianfan: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
  nvidia: "https://build.nvidia.com/settings/api-keys",
  deepseek: "https://platform.deepseek.com/api_keys",
  alibaba: "https://bailian.console.aliyun.com/",
  "alibaba-coding-plan": "https://bailian.console.aliyun.com/",
  "qwen-token-plan": "https://bailian.console.aliyun.com/",
  "qwen-token-plan-cn": "https://bailian.console.aliyun.com/",
  cerebras: "https://cloud.cerebras.ai/platform/",
  cohere: "https://dashboard.cohere.com/api-keys",
  mistral: "https://console.mistral.ai/api-keys/",
  deepinfra: "https://deepinfra.com/dash/api_keys",
  fireworks: "https://app.fireworks.ai/settings/users/api-keys",
  novita: "https://novita.ai/settings/key-management",
  stepfun: "https://platform.stepfun.com/interface-key",
  tencent: "https://console.cloud.tencent.com/",
  volcengine: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
  byteplus: "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey",
  gmi: "https://console.gmicloud.ai/user/api-key/manage",
  kilocode: "https://app.kilo.ai/",
  "opencode-go": "https://opencode.ai/auth",
  "ollama-cloud": "https://ollama.com/settings/keys",
  devin: "https://app.devin.ai/settings/api-keys",
};

export function providerApiConsoleUrl(providerType: string): string | null {
  return providerApiConsoleUrls[providerType] ?? null;
}

export function providerTypesWithApiConsole(): string[] {
  return Object.keys(providerApiConsoleUrls);
}
