export const integrationProviderCatalog = {
  custom: {
    name: "Custom Provider",
    baseUrl: "",
    api: "openai-completions",
    authType: "api_key",
    models: [],
  },
  together: {
    name: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "Qwen/Qwen2.5-7B-Instruct-Turbo",
        name: "Qwen2.5 7B Instruct Turbo",
        context: 32768,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "deepseek-ai/DeepSeek-V4-Pro",
        name: "DeepSeek V4 Pro",
        context: 512000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM 5.1",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-4.7",
        name: "GLM 4.7 Fp8",
        context: 202752,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B 16E Instruct",
        context: 10000000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        name: "Llama 4 Maverick 17B 128E Instruct FP8",
        context: 20000000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2-Instruct 0905",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  huggingface: {
    name: "Hugging Face",
    baseUrl: "https://router.huggingface.co/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "moonshotai/Kimi-K2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "Qwen/Qwen3.5-397B-A17B",
        name: "Qwen3.5 397B A17B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 192000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-5",
        name: "GLM-5",
        context: 256000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "XiaomiMiMo/MiMo-V2-Flash",
        name: "Xiaomi MiMo V2 Flash",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  synthetic: {
    name: "Synthetic",
    baseUrl: "https://api.synthetic.new/anthropic",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "hf:zai-org/GLM-5",
        name: "GLM-5",
        context: 256000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "hf:MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 192000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        context: 256000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "hf:zai-org/GLM-4.6",
        name: "GLM-4.6",
        context: 198000,
        maxTokens: 128000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        context: 159000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:MiniMaxAI/MiniMax-M2.1",
        name: "MiniMax M2.1 (HF)",
        context: 192000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:moonshotai/Kimi-K2-Thinking",
        name: "Kimi K2 Thinking",
        context: 256000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "hf:zai-org/GLM-4.7",
        name: "GLM-4.7",
        context: 198000,
        maxTokens: 128000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:deepseek-ai/DeepSeek-R1-0528",
        name: "DeepSeek R1 0528",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B Instruct",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:Qwen/Qwen3-235B-A22B-Instruct-2507",
        name: "Qwen3 235B A22B",
        context: 256000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hf:Qwen/Qwen3-Coder-480B-A35B-Instruct",
        name: "Qwen3 Coder 480B",
        context: 256000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  venice: {
    name: "Venice AI",
    baseUrl: "https://api.venice.ai/api/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "llama-3.2-3b",
        name: "Llama 3.2 3B",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "hermes-3-llama-3.1-405b",
        name: "Hermes 3 Llama 3.1 405B",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-235b-a22b-instruct-2507",
        name: "Qwen3 235B Instruct",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-coder-480b-a35b-instruct-turbo",
        name: "Qwen3 Coder 480B Turbo",
        context: 256000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-5-35b-a3b",
        name: "Qwen3.5 35B A3B",
        context: 256000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3-next-80b",
        name: "Qwen3 Next 80B",
        context: 256000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-4b",
        name: "Venice Small (Qwen3 4B)",
        context: 32000,
        maxTokens: 4096,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "venice-uncensored",
        name: "Venice Uncensored (Dolphin-Mistral)",
        context: 32000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "mistral-31-24b",
        name: "Venice Medium (Mistral)",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "google-gemma-3-27b-it",
        name: "Google Gemma 3 27B Instruct",
        context: 198000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-oss-120b",
        name: "OpenAI GPT OSS 120B",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia-nemotron-3-nano-30b-a3b",
        name: "NVIDIA Nemotron 3 Nano 30B",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "olafangensan-glm-4.7-flash-heretic",
        name: "GLM 4.7 Flash Heretic",
        context: 128000,
        maxTokens: 24000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org-glm-4.6",
        name: "GLM 4.6",
        context: 198000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "zai-org-glm-4.7-flash",
        name: "GLM 4.7 Flash",
        context: 128000,
        maxTokens: 16384,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2-5",
        name: "Kimi K2.5",
        context: 256000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        context: 256000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m21",
        name: "MiniMax M2.1",
        context: 198000,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m25",
        name: "MiniMax M2.5",
        context: 198000,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6 (via Venice)",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6 (via Venice)",
        context: 1000000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-53-codex",
        name: "GPT-5.3 Codex (via Venice)",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-54",
        name: "GPT-5.4 (via Venice)",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-4o-2024-11-20",
        name: "GPT-4o (via Venice)",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-4o-mini-2024-07-18",
        name: "GPT-4o Mini (via Venice)",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-1-pro-preview",
        name: "Gemini 3.1 Pro (via Venice)",
        context: 1000000,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "zai-org-glm-5",
        name: "GLM-5 (via Venice)",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen3.5-397b-a22b",
        name: "Qwen3.5 397B (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m3",
        name: "MiniMax M3 (via Venice)",
        context: 1000000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-55",
        name: "GPT-5.5 (via Venice)",
        context: 272000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-235b-a22b-thinking-2507",
        name: "Qwen3 235B Thinking",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen3-coder-480b-a35b-instruct",
        name: "Qwen3 Coder 480B",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-vl-235b-a22b",
        name: "Qwen3 VL 235B (Vision)",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        context: 163840,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org-glm-4.7",
        name: "GLM 4.7",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "claude-opus-45",
        name: "Claude Opus 4.5 (via Venice)",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-45",
        name: "Claude Sonnet 4.5 (via Venice)",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai-gpt-52",
        name: "GPT-5.2 (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai-gpt-52-codex",
        name: "GPT-5.2 Codex (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro (via Venice)",
        context: 202752,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "grok-41-fast",
        name: "Grok 4.1 Fast (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "grok-code-fast-1",
        name: "Grok Code Fast 1 (via Venice)",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  xiaomi: {
    name: "Xiaomi MiMo",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "mimo-v2.5-pro",
        name: "Xiaomi MiMo V2.5 Pro",
        context: 1048576,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "mimo-v2.5",
        name: "Xiaomi MiMo V2.5",
        context: 1048576,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "mimo-v2-pro",
        name: "Xiaomi MiMo V2 Pro",
        context: 1048576,
        maxTokens: 32000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "mimo-v2-omni",
        name: "Xiaomi MiMo V2 Omni",
        context: 262144,
        maxTokens: 32000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "mimo-v2-flash",
        name: "Xiaomi MiMo V2 Flash",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  ollama: {
    name: "Ollama (Local)",
    baseUrl: "http://localhost:11434/v1",
    api: "ollama",
    authType: "none",
    models: [],
  },
  vllm: {
    name: "vLLM (Local)",
    baseUrl: "http://127.0.0.1:8000/v1",
    api: "openai-completions",
    authType: "none",
    models: [],
  },
  azure: {
    name: "Azure OpenAI",
    baseUrl: "https://YOUR-RESOURCE.openai.azure.com/openai/v1",
    api: "openai-completions",
    authType: "api_key",
    apiKeyHeader: "api-key",
    models: [],
  },
  azure_foundry: {
    name: "Azure AI Foundry",
    baseUrl: "https://YOUR-RESOURCE.services.ai.azure.com/models",
    api: "openai-completions",
    authType: "api_key",
    apiKeyHeader: "api-key",
    models: [],
  },
  anthropic_vertex: {
    name: "Anthropic (Vertex AI)",
    baseUrl:
      "https://us-east5-aiplatform.googleapis.com/v1/projects/YOUR_PROJECT/locations/us-east5/publishers/anthropic/models",
    api: "anthropic-vertex",
    authType: "api_key",
    models: [],
  },
  google_vertex: {
    name: "Google Gemini (Vertex AI)",
    baseUrl:
      "https://us-central1-aiplatform.googleapis.com/v1/projects/YOUR_PROJECT/locations/us-central1/publishers/google",
    api: "google-vertex",
    authType: "api_key",
    models: [],
  },
  litellm: {
    name: "LiteLLM",
    baseUrl: "http://127.0.0.1:4000/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [],
  },
  lmstudio: {
    name: "LM Studio (Local)",
    baseUrl: "http://127.0.0.1:1234/v1",
    api: "openai-completions",
    authType: "none",
    models: [],
  },
  sglang: {
    name: "SGLang (Local)",
    baseUrl: "http://127.0.0.1:30000/v1",
    api: "openai-completions",
    authType: "none",
    models: [],
  },
  llamacpp: {
    name: "llama.cpp (Local)",
    baseUrl: "http://127.0.0.1:8080/v1",
    api: "openai-completions",
    authType: "none",
    models: [],
  },
  perplexity: {
    name: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "sonar",
        name: "Sonar",
        context: 128000,
        maxTokens: 8000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        context: 200000,
        maxTokens: 8000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "sonar-reasoning-pro",
        name: "Sonar Reasoning Pro",
        context: 128000,
        maxTokens: 8000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  arcee: {
    name: "Arcee",
    baseUrl: "https://conductor.arcee.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [],
  },
  nous: {
    name: "Nous Research",
    baseUrl: "https://inference-api.nousresearch.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "Hermes-4-405B",
        name: "Hermes 4 405B",
        context: 128000,
        maxTokens: 16000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Hermes-4-70B",
        name: "Hermes 4 70B",
        context: 128000,
        maxTokens: 16000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "cloudflare-ai-gateway": {
    name: "Cloudflare AI Gateway",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/anthropic",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  github_copilot: {
    name: "GitHub Copilot",
    baseUrl: "https://api.github.com/copilot",
    api: "github-copilot",
    authType: "oauth",
    oauthFlow: "device_code" as const,
    oauthConfig: {
      clientId: "Iv1.b507a08c87ecfe98",
      deviceCodeUrl: "https://github.com/login/device/code",
      tokenUrl: "https://github.com/login/oauth/access_token",
      scope: "read:user",
    },
    models: [
      {
        id: "goldeneye",
        name: "Goldeneye",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "raptor-mini",
        name: "Raptor Mini",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 Nano",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "claude-opus-4.8",
        name: "Claude Opus 4.8",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4.7",
        name: "Claude Opus 4.7",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4.6",
        name: "Claude Opus 4.6",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-flash",
        name: "Gemini 3 Flash",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-4o",
        name: "gpt-4o",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gpt-4.1",
        name: "gpt-4.1",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gpt-4.1-mini",
        name: "gpt-4.1-mini",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gpt-4.1-nano",
        name: "gpt-4.1-nano",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "o1",
        name: "o1",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "o1-mini",
        name: "o1-mini",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  bedrock: {
    name: "AWS Bedrock",
    baseUrl: "https://bedrock-runtime.{region}.amazonaws.com",
    api: "bedrock-converse-stream",
    authType: "aws-sdk",
    models: [],
  },
} as const;
