export const commandcodeProvider = {
  name: "Command Code",
  baseUrl: "https://api.commandcode.ai/provider/v1",
  api: "openai-completions",
  authType: "api_key",
  models: [
    {
      id: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-fable-5",
      name: "Claude Fable 5",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-opus-5",
      name: "Claude Opus 5",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-opus-4-8",
      name: "Claude Opus 4.8",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-opus-4-7",
      name: "Claude Opus 4.7",
      api: "anthropic-messages",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "claude-haiku-4-5-20251001",
      name: "Claude Haiku 4.5",
      api: "anthropic-messages",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      context: 1050000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6 Terra",
      context: 1050000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      context: 1050000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      context: 400000,
      maxTokens: 100000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3 Codex",
      context: 400000,
      maxTokens: 100000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 Mini",
      context: 400000,
      maxTokens: 100000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "deepseek/deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K3",
      name: "Kimi K3",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K2.7-Code",
      name: "Kimi K2.7 Code",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K2.7-Code-Highspeed",
      name: "Kimi K2.7 Code HighSpeed",
      context: 262000,
      maxTokens: 65500,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K2.6",
      name: "Kimi K2.6",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K2.5",
      name: "Kimi K2.5",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "zai-org/GLM-5.2",
      name: "GLM-5.2",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "zai-org/GLM-5.2-Fast",
      name: "GLM-5.2 Fast",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "zai-org/GLM-5.1",
      name: "GLM-5.1",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "zai-org/GLM-5",
      name: "GLM-5",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "MiniMaxAI/MiniMax-M3",
      name: "MiniMax M3",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "MiniMaxAI/MiniMax-M2.7",
      name: "MiniMax M2.7",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "MiniMaxAI/MiniMax-M2.5",
      name: "MiniMax M2.5",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "xiaomi/mimo-v2.5-pro",
      name: "MiMo V2.5 Pro",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "xiaomi/mimo-v2.5",
      name: "MiMo V2.5",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "Qwen/Qwen3.6-Max-Preview",
      name: "Qwen 3.6 Max Preview",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "Qwen/Qwen3.6-Plus",
      name: "Qwen 3.6 Plus",
      context: 200000,
      maxTokens: 50000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "Qwen/Qwen3.7-Max",
      name: "Qwen 3.7 Max",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "Qwen/Qwen3.7-Plus",
      name: "Qwen 3.7 Plus",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "Qwen/Qwen3.7-Flash",
      name: "Qwen 3.7 Flash",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "Qwen/Qwen3.8-Max",
      name: "Qwen 3.8 Max",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "stepfun/Step-3.7-Flash",
      name: "Step 3.7 Flash",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "stepfun/Step-3.5-Flash",
      name: "Step 3.5 Flash",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "tencent/hy3-paid",
      name: "Tencent Hy3",
      context: 262144,
      maxTokens: 65536,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "google/gemini-3.6-flash",
      name: "Gemini 3.6 Flash",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "google/gemini-3.5-flash",
      name: "Gemini 3.5 Flash",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "google/gemini-3.5-flash-lite",
      name: "Gemini 3.5 Flash Lite",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "google/gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "sakana/fugu-ultra",
      name: "Fugu Ultra",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "nvidia/nemotron-3-ultra-550b-a55b",
      name: "Nemotron 3 Ultra",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "thinkingmachines/inkling",
      name: "Inkling",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "thinkingmachines/inkling-small",
      name: "Inkling Small",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "poolside/laguna-s-2.1-free",
      name: "Laguna S 2.1",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "inclusionai/ling-3.0-flash-free",
      name: "Ling 3.0 Flash",
      context: 256000,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "meta/muse-spark-1.1",
      name: "Muse Spark 1.1",
      context: 1048576,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "xai/grok-4.5",
      name: "Grok 4.5",
      context: 500000,
      maxTokens: 125000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "xai/grok-4.6",
      name: "Grok 4.6",
      context: 500000,
      maxTokens: 125000,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "google/gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      context: 1048576,
      maxTokens: 65536,
      reasoning: true,
      input: ["text", "image", "audio", "video", "pdf"],
    },
    {
      id: "google/gemini-3.8-flash",
      name: "Gemini 3.8 Flash",
      context: 1048576,
      maxTokens: 65536,
      reasoning: true,
      input: ["text", "image", "audio", "video", "pdf"],
    },
    {
      id: "anthropic/claude-fable-5.1",
      name: "Claude Fable 5.1",
      context: 1000000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image", "pdf"],
    },
    {
      id: "tencent/hy4-preview",
      name: "HunYuan4 Preview",
      context: 1048576,
      maxTokens: 64000,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "meta/muse-spark-1.2",
      name: "Muse Spark 1.2",
      context: 1048576,
      maxTokens: 131072,
      reasoning: true,
      input: ["text", "image", "audio", "video", "pdf"],
    },
    {
      id: "meta/muse-spark-1.3",
      name: "Muse Spark 1.3",
      context: 1048576,
      maxTokens: 131072,
      reasoning: true,
      input: ["text", "image", "audio", "video", "pdf"],
    },
    {
      id: "poolside/laguna-s-2.1",
      name: "Laguna S 2.1",
      context: 1048576,
      maxTokens: 32768,
      reasoning: true,
      input: ["text"],
    },
  ],
} as const;
