import { MINIMAX_OAUTH_CLIENT_ID, MINIMAX_OAUTH_SCOPE } from "./minimax-oauth";

const miniMaxPortalModels = [
  {
    id: "MiniMax-M3",
    name: "MiniMax M3",
    context: 1000000,
    maxTokens: 131072,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "MiniMax-M2.7",
    name: "MiniMax M2.7",
    context: 204800,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "MiniMax-M2.5",
    name: "MiniMax M2.5",
    context: 204800,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "MiniMax-M2.5-highspeed",
    name: "MiniMax M2.5 HighSpeed",
    context: 204800,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "MiniMax-M2",
    name: "MiniMax M2",
    context: 204800,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "MiniMax-M2.1",
    name: "MiniMax M2.1",
    context: 204800,
    maxTokens: 64000,
    reasoning: false,
    input: ["text"],
  },
  {
    id: "MiniMax-M2.1-highspeed",
    name: "MiniMax M2.1 HighSpeed",
    context: 204800,
    maxTokens: 64000,
    reasoning: false,
    input: ["text"],
  },
] as const;

export const foundationProviderCatalog = {
  openai: {
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    api: "openai-responses",
    authType: "api_key",
    models: [
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6",
        name: "GPT-5.6 (Sol alias)",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 Nano",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.3-chat-latest",
        name: "GPT-5.3 Chat (latest)",
        context: 128000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        context: 400000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5-mini",
        name: "GPT-5 Mini",
        context: 200000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        context: 400000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        context: 400000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        context: 400000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "o1",
        name: "o1",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o1-pro",
        name: "o1-pro",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o3",
        name: "o3",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o3-deep-research",
        name: "o3 Deep Research",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "o3-pro",
        name: "o3-pro",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o4-mini",
        name: "o4-mini",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "o4-mini-deep-research",
        name: "o4-mini Deep Research",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  elevenlabs: {
    name: "ElevenLabs",
    baseUrl: "https://api.elevenlabs.io/v1",
    api: "elevenlabs-speech",
    authType: "api_key",
    models: [
      {
        id: "eleven_multilingual_v2",
        name: "Eleven Multilingual v2",
        context: 5000,
        maxTokens: 5000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "eleven_flash_v2_5",
        name: "Eleven Flash v2.5",
        context: 5000,
        maxTokens: 5000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "eleven_turbo_v2_5",
        name: "Eleven Turbo v2.5",
        context: 5000,
        maxTokens: 5000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "eleven_v3",
        name: "Eleven v3",
        context: 5000,
        maxTokens: 5000,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  meta: {
    name: "Meta AI",
    baseUrl: "https://api.ai.meta.com/v1",
    api: "openai-responses",
    authType: "api_key",
    models: [
      {
        id: "muse-spark-1.1",
        name: "Muse Spark 1.1",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  anthropic: {
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "claude-mythos-5",
        name: "Claude Mythos 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-haiku-4-5-20251001",
        name: "Claude Haiku 4.5 (2025-10-01)",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4",
        name: "Claude Opus 4",
        context: 200000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-sonnet-4",
        name: "Claude Sonnet 4",
        context: 200000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  google: {
    name: "Google AI",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    api: "google-generative-ai",
    authType: "api_key",
    models: [
      {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.0-flash-exp",
        name: "Gemini 2.0 Flash Exp",
        context: 1048576,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image", "audio", "video"],
      },
    ],
  },
  antigravity: {
    name: "Antigravity",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    api: "google-generative-ai",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthConfig: {
      clientId:
        process.env.CYBARA_ANTIGRAVITY_OAUTH_CLIENT_ID?.trim() ||
        "1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com",
      clientSecret:
        process.env.CYBARA_ANTIGRAVITY_OAUTH_CLIENT_SECRET?.trim() ||
        "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",
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scope:
        "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/cclog https://www.googleapis.com/auth/experimentsandconfigs",
      callbackPort: 51121,
      callbackPath: "/oauth-callback",
    },
    models: [
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3.1-pro-preview-customtools",
        name: "Gemini 3.1 Pro Custom Tools (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash (Antigravity)",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  minimax: {
    name: "MiniMax",
    baseUrl: "https://api.minimax.io/anthropic/v1",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "MiniMax-M3",
        name: "MiniMax M3",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "MiniMax-M2.7",
        name: "MiniMax M2.7",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.7-highspeed",
        name: "MiniMax M2.7 HighSpeed",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.7-lightning",
        name: "MiniMax M2.7 Lightning",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.5-highspeed",
        name: "MiniMax M2.5 HighSpeed",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.5-Lightning",
        name: "MiniMax M2.5 Lightning (Legacy Alias)",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2",
        name: "MiniMax M2",
        context: 204800,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.1",
        name: "MiniMax M2.1",
        context: 204800,
        maxTokens: 64000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.1-highspeed",
        name: "MiniMax M2.1 HighSpeed",
        context: 204800,
        maxTokens: 64000,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMax-VL-01",
        name: "MiniMax VL 01",
        context: 204800,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "MiniMax-M2.1-lightning",
        name: "MiniMax M2.1 Lightning (Legacy Alias)",
        context: 204800,
        maxTokens: 64000,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  "minimax-portal": {
    name: "MiniMax Portal",
    baseUrl: "https://api.minimax.io/anthropic/v1",
    api: "anthropic-messages",
    authType: "oauth",
    oauthFlow: "device_code" as const,
    oauthConfig: {
      clientId: MINIMAX_OAUTH_CLIENT_ID,
      deviceCodeUrl: "https://account.minimax.io/oauth2/device/code",
      tokenUrl: "https://account.minimax.io/oauth2/token",
      scope: MINIMAX_OAUTH_SCOPE,
    },
    oauthLoginUrl: "https://account.minimax.io/",
    models: miniMaxPortalModels,
  },
  "minimax-portal-cn": {
    name: "MiniMax Portal China",
    baseUrl: "https://api.minimaxi.com/anthropic/v1",
    api: "anthropic-messages",
    authType: "oauth",
    oauthFlow: "device_code" as const,
    oauthConfig: {
      clientId: MINIMAX_OAUTH_CLIENT_ID,
      deviceCodeUrl: "https://account.minimaxi.com/oauth2/device/code",
      tokenUrl: "https://account.minimaxi.com/oauth2/token",
      scope: MINIMAX_OAUTH_SCOPE,
    },
    oauthLoginUrl: "https://account.minimaxi.com/",
    models: miniMaxPortalModels,
  },
  moonshot: {
    name: "Moonshot AI",
    baseUrl: "https://api.moonshot.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2-thinking-turbo",
        name: "Kimi K2 Thinking Turbo",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2-turbo",
        name: "Kimi K2 Turbo",
        context: 256000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2-0905-preview",
        name: "Kimi K2 0905 Preview",
        context: 256000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  "kimi-code": {
    name: "Kimi Code",
    baseUrl: "https://api.kimi.com/coding/v1",
    api: "openai-completions",
    authType: "api_key",
    headers: { "User-Agent": "KimiCLI/0.77" },
    models: [
      {
        id: "kimi-for-coding",
        name: "Kimi For Coding",
        context: 262144,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "qwen-portal": {
    name: "Qwen Portal",
    baseUrl: "https://portal.qwen.ai/v1",
    api: "openai-completions",
    authType: "token",
    oauthLoginUrl: "https://chat.qwen.ai/",
    models: [
      {
        id: "qwen3.5-plus",
        name: "Qwen 3.5 Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen 3.6 Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3-max-2026-01-23",
        name: "Qwen 3 Max 2026-01-23",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-coder-next",
        name: "Qwen 3 Coder Next",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-coder-plus",
        name: "Qwen 3 Coder Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5",
        name: "GLM 5",
        context: 202752,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "glm-4.7",
        name: "GLM 4.7",
        context: 202752,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
} as const;
