export const QWEN_TOKEN_PLAN_MODELS = [
  {
    id: "qwen3.8-flash",
    name: "Qwen3.8 Flash",
    context: 1000000,
    maxTokens: 131072,
    reasoning: true,
    input: ["text", "image", "video"],
  },
  {
    id: "qwen3.8-max",
    name: "Qwen3.8 Max",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
] as const;
