export const codingProviderCatalog = {
  groq: {
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        context: 128000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        context: 32768,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "gemma-7b-it",
        name: "Gemma 7B",
        context: 32768,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  openrouter: {
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "anthropic/claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-sonnet-5",
        name: "Claude Sonnet 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax/minimax-m3",
        name: "MiniMax M3",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "z-ai/glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "anthropic/claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-5.2",
        name: "GPT-5.2",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  opencode_zen: {
    name: "OpenCode Zen",
    baseUrl: "https://opencode.ai/zen/v1",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m2.7",
        name: "MiniMax M2.7",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen3-coder",
        name: "Qwen3 Coder",
        context: 262144,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-pro",
        name: "Gemini 3 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-flash",
        name: "Gemini 3 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "z.ai": {
    name: "Z.AI (Zhipu)",
    baseUrl: "https://api.z.ai/api/paas/v4",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5-turbo",
        name: "GLM-5 Turbo",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5v-turbo",
        name: "GLM-5V Turbo",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.5-air",
        name: "GLM-4.5 Air",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.7-flash",
        name: "GLM-4.7 Flash",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  "z.ai-coding": {
    name: "Z.AI Coding Plan",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "glm-5.2",
        name: "GLM-5.2 (Coding)",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1 (Coding)",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-5",
        name: "GLM-5 (Coding)",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7 (Coding)",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5 (Coding)",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
        code: true,
      },
    ],
  },
  "openai-codex": {
    name: "OpenAI Codex (ChatGPT OAuth)",
    baseUrl: "https://chatgpt.com/backend-api",
    api: "openai-codex-responses",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthConfig: {
      clientId: "app_EMoamEEZ73f0CkXaXp7hrann",
      authorizeUrl: "https://auth.openai.com/oauth/authorize",
      tokenUrl: "https://auth.openai.com/oauth/token",
      scope: "openid profile email offline_access",
      callbackPort: 1455,
      callbackPath: "/auth/callback",
      authorizeParams: {
        id_token_add_organizations: "true",
        codex_cli_simplified_flow: "true",
        originator: "cybara",
      },
    },
    oauthLoginUrl: "https://chatgpt.com/",
    models: [
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        context: 128000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
    ],
  },
  chutes: {
    name: "Chutes",
    baseUrl: "https://llm.chutes.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    oauthLoginUrl: "https://chutes.ai/app/api-keys",
    models: [],
  },
  "vercel-ai-gateway": {
    name: "Vercel AI Gateway",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "google-gemini-cli": {
    name: "Google Gemini CLI",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    api: "google-generative-ai",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthConfig: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scope:
        "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
      callbackPort: 8085,
      callbackPath: "/oauth2callback",
    },
    oauthLoginUrl: "https://github.com/google-gemini/gemini-cli",
    models: [
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        context: 1048576,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash",
        context: 1048576,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image", "audio", "video"],
      },
    ],
  },
  "copilot-proxy": {
    name: "Copilot Proxy",
    baseUrl: "http://localhost:1234/v1",
    api: "openai-completions",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthLoginUrl: "https://github.com/settings/copilot",
    models: [],
  },
} as const;
