import { getAppVersion } from "../build-info";

const XAI_OAUTH_DISCOVERY_URL = "https://auth.x.ai/.well-known/openid-configuration";
const XAI_OAUTH_CLIENT_ID = "b1a00492-073a-47ea-816f-4c329264a828";
const XAI_OAUTH_SCOPE =
  "openid profile email offline_access grok-cli:access api:access conversations:read conversations:write";
const XAI_GROK_PROXY_BASE_URL = "https://cli-chat-proxy.grok.com/v1";

const QWEN_TOKEN_PLAN_MODELS = [
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "qwen3.7-plus",
    name: "Qwen3.7 Plus",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "qwen3.6-plus",
    name: "Qwen3.6 Plus",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "qwen3.6-flash",
    name: "Qwen3.6 Flash",
    context: 1000000,
    maxTokens: 65536,
    reasoning: true,
    input: ["text", "image"],
  },
] as const;

const XAI_GROK_MODELS = [
  {
    id: "grok-build",
    name: "Grok Build",
    context: 500000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text", "image"],
    code: true,
  },
  {
    id: "grok-build-0.1",
    name: "Grok Build 0.1",
    context: 256000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text", "image"],
    code: true,
  },
  {
    id: "grok-4.20-0309-reasoning",
    name: "Grok 4.20 0309 (Reasoning)",
    context: 1000000,
    maxTokens: 30000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-4.20-0309-non-reasoning",
    name: "Grok 4.20 0309 (Non-Reasoning)",
    context: 1000000,
    maxTokens: 30000,
    reasoning: false,
    input: ["text", "image"],
  },
  {
    id: "grok-4.20-multi-agent-0309",
    name: "Grok 4.20 Multi-Agent 0309",
    context: 1000000,
    maxTokens: 30000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-3",
    name: "Grok 3",
    context: 131072,
    maxTokens: 8192,
    reasoning: false,
    input: ["text"],
  },
  {
    id: "grok-3-fast",
    name: "Grok 3 Fast",
    context: 131072,
    maxTokens: 8192,
    reasoning: false,
    input: ["text"],
  },
  {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    context: 131072,
    maxTokens: 8192,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "grok-3-mini-fast",
    name: "Grok 3 Mini Fast",
    context: 131072,
    maxTokens: 8192,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "grok-4.3",
    name: "Grok 4.3",
    context: 1000000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-4.5",
    name: "Grok 4.5",
    context: 500000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text", "image"],
    code: true,
  },
  {
    id: "grok-4.20-beta-latest-reasoning",
    name: "Grok 4.20 Beta Latest (Reasoning)",
    context: 1000000,
    maxTokens: 30000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-4.20-beta-latest-non-reasoning",
    name: "Grok 4.20 Beta Latest (Non-Reasoning)",
    context: 1000000,
    maxTokens: 30000,
    reasoning: false,
    input: ["text", "image"],
  },
  {
    id: "grok-4",
    name: "Grok 4",
    context: 256000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "grok-4-0709",
    name: "Grok 4 0709",
    context: 256000,
    maxTokens: 64000,
    reasoning: false,
    input: ["text"],
  },
  {
    id: "grok-4-heavy",
    name: "Grok 4 Heavy",
    context: 256000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
  },
  {
    id: "grok-4-fast",
    name: "Grok 4 Fast",
    context: 2000000,
    maxTokens: 30000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-4-fast-non-reasoning",
    name: "Grok 4 Fast (Non-Reasoning)",
    context: 2000000,
    maxTokens: 30000,
    reasoning: false,
    input: ["text", "image"],
  },
  {
    id: "grok-4-1-fast",
    name: "Grok 4.1 Fast",
    context: 2000000,
    maxTokens: 30000,
    reasoning: true,
    input: ["text", "image"],
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast (Non-Reasoning)",
    context: 2000000,
    maxTokens: 30000,
    reasoning: false,
    input: ["text", "image"],
  },
  {
    id: "grok-code-fast-1",
    name: "Grok Code Fast 1",
    context: 256000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text"],
    code: true,
  },
] as const;

const XAI_GROK_OAUTH_MODELS = [
  XAI_GROK_MODELS[0],
  {
    id: "grok-composer-2.5-fast",
    name: "Grok Composer 2.5 Fast",
    context: 200000,
    maxTokens: 64000,
    reasoning: true,
    input: ["text", "image"],
    code: true,
  },
  ...XAI_GROK_MODELS.slice(1),
] as const;

export const cloudProviderCatalog = {
  ds4: {
    name: "ds4",
    baseUrl: "http://127.0.0.1:18000/v1",
    api: "openai-completions",
    authType: "none",
    models: [
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash (ds4)",
        context: 32768,
        maxTokens: 128,
        reasoning: true,
        input: ["text"],
        code: true,
      },
    ],
  },
  inferrs: {
    name: "Inferrs",
    baseUrl: "http://127.0.0.1:8080/v1",
    api: "openai-completions",
    authType: "none",
    models: [
      {
        id: "google/gemma-4-E2B-it",
        name: "Gemma 4 E2B (Inferrs)",
        context: 131072,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  featherless: {
    name: "Featherless AI",
    baseUrl: "https://api.featherless.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen3 32B",
        context: 131072,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  longcat: {
    name: "LongCat",
    baseUrl: "https://api.longcat.chat/openai",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "LongCat-2.0",
        name: "LongCat 2.0",
        context: 1048576,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "meituan/longcat-2.0",
        name: "LongCat 2.0",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
    ],
  },
  xai: {
    name: "xAI (Grok)",
    baseUrl: "https://api.x.ai/v1",
    api: "openai-responses",
    authType: "api_key",
    models: XAI_GROK_MODELS,
  },
  "xai-oauth": {
    name: "xAI Grok OAuth",
    baseUrl: XAI_GROK_PROXY_BASE_URL,
    api: "xai-grok-responses",
    authType: "oauth",
    headers: {
      "X-XAI-Token-Auth": "xai-grok-cli",
      "x-authenticateresponse": "authenticate-response",
      "x-grok-client-identifier": "cybara",
      "x-grok-client-mode": "interactive",
      "x-grok-client-version": getAppVersion(),
      "User-Agent": `Cybara/${getAppVersion()}`,
    },
    oauthFlow: "device_code" as const,
    oauthConfig: {
      clientId: XAI_OAUTH_CLIENT_ID,
      discoveryUrl: XAI_OAUTH_DISCOVERY_URL,
      deviceCodeDiscoveryUrl: XAI_OAUTH_DISCOVERY_URL,
      tokenUrl: "https://auth.x.ai/oauth2/token",
      scope: XAI_OAUTH_SCOPE,
    },
    models: XAI_GROK_OAUTH_MODELS,
  },
  qianfan: {
    name: "Baidu Qianfan",
    baseUrl: "https://qianfan.baidubce.com/v2",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "deepseek-v3.2",
        name: "DEEPSEEK V3.2",
        context: 98304,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "ernie-5.0-thinking-preview",
        name: "ERNIE-5.0-Thinking-Preview",
        context: 119000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "ernie-5.0",
        name: "ERNIE 5.0",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "ernie-4.5",
        name: "ERNIE 4.5",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "ernie-x1",
        name: "ERNIE X1",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "ernie-speed",
        name: "ERNIE Speed",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "ernie-lite",
        name: "ERNIE Lite",
        context: 131072,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  nvidia: {
    name: "NVIDIA",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "deepseek-ai/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 262144,
        maxTokens: 16384,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimaxai/minimax-m2.5",
        name: "MiniMax M2.5",
        context: 196608,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "minimaxai/minimax-m3",
        name: "MiniMax M3",
        context: 196608,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "z-ai/glm-5.2",
        name: "GLM 5.2",
        context: 202752,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "z-ai/glm5",
        name: "GLM-5",
        context: 202752,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia/nemotron-3-ultra-550b-a55b",
        name: "NVIDIA Nemotron 3 Ultra 550B",
        context: 1000000,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "NVIDIA Nemotron 3 Super 120B",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia/nemotron-3-nano-30b-a3b",
        name: "NVIDIA Nemotron 3 Nano 30B",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen/qwen3.5-397b-a17b",
        name: "Qwen3.5 397B A17B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-ai/deepseek-v3.2",
        name: "DeepSeek V3.2",
        context: 163840,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "moonshotai/kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "minimaxai/minimax-m2.7",
        name: "MiniMax M2.7",
        context: 196608,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "z-ai/glm-5.1",
        name: "GLM 5.1",
        context: 202752,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia/llama-3.1-nemotron-70b-instruct",
        name: "NVIDIA Llama 3.1 Nemotron 70B Instruct",
        context: 131072,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  deepseek: {
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat (V4 Flash)",
        context: 1000000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner (V4 Flash Thinking)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  alibaba: {
    name: "Alibaba DashScope",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "qwen3.7-max",
        name: "Qwen3.7 Max",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen3.7-plus",
        name: "Qwen3.7 Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3.6-flash",
        name: "Qwen3.6 Flash",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "qwen3-coder-plus",
        name: "Qwen3 Coder Plus",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "qwen3-coder-next",
        name: "Qwen3 Coder Next",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 202752,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "alibaba-coding-plan": {
    name: "Alibaba Coding Plan",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "qwen3.7-plus",
        name: "Qwen3.7 Plus (Coding)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus (Coding)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus (Coding)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "qwen3-coder-plus",
        name: "Qwen3 Coder Plus (Coding)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "qwen3-coder-next",
        name: "Qwen3 Coder Next (Coding)",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5 (Coding)",
        context: 262144,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-5",
        name: "GLM-5 (Coding)",
        context: 202752,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7 (Coding)",
        context: 202752,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
        code: true,
      },
      {
        id: "MiniMax-M2.5",
        name: "MiniMax M2.5 (Coding)",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
        code: true,
      },
    ],
  },
  "qwen-token-plan": {
    name: "Qwen Token Plan",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    api: "openai-completions",
    authType: "api_key",
    models: QWEN_TOKEN_PLAN_MODELS,
  },
  "qwen-token-plan-cn": {
    name: "Qwen Token Plan (China)",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    api: "openai-completions",
    authType: "api_key",
    models: QWEN_TOKEN_PLAN_MODELS,
  },
  cerebras: {
    name: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "zai-glm-4.7",
        name: "GLM-4.7",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "gpt-oss-120b",
        name: "GPT-OSS 120B",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen-3-235b-a22b-instruct-2507",
        name: "Qwen3 235B A22B",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "llama3.1-8b",
        name: "Llama 3.1 8B",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  cohere: {
    name: "Cohere",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "command-a-plus-05-2026",
        name: "Command A+",
        context: 128000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "command-a-reasoning-08-2025",
        name: "Command A Reasoning",
        context: 256000,
        maxTokens: 32000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "command-a-vision-07-2025",
        name: "Command A Vision",
        context: 128000,
        maxTokens: 8000,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "north-mini-code-1-0",
        name: "North Mini Code 1.0",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "command-a-03-2025",
        name: "Command A",
        context: 256000,
        maxTokens: 8000,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  mistral: {
    name: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "mistral-small-2603",
        name: "Mistral Small 4 (26.03)",
        context: 262144,
        maxTokens: 16384,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "devstral-medium-latest",
        name: "Devstral 2",
        context: 262144,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        context: 256000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "magistral-small",
        name: "Magistral Small",
        context: 128000,
        maxTokens: 40000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        context: 262144,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "mistral-medium-2508",
        name: "Mistral Medium 3.1",
        context: 262144,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "mistral-medium-3-5",
        name: "Mistral Medium 3.5",
        context: 262144,
        maxTokens: 8192,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        context: 128000,
        maxTokens: 16384,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "pixtral-large-latest",
        name: "Pixtral Large",
        context: 128000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  deepinfra: {
    name: "DeepInfra",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        name: "NVIDIA Nemotron 3 Super 120B A12B",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V4-Flash",
        name: "DeepSeek V4 Flash",
        context: 1048576,
        maxTokens: 1048576,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        context: 163840,
        maxTokens: 163840,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-5.1",
        name: "GLM 5.1",
        context: 202752,
        maxTokens: 202752,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "stepfun-ai/Step-3.5-Flash",
        name: "Step-3.5 Flash",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5",
        name: "MiniMax M2.5",
        context: 196608,
        maxTokens: 196608,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Instruct Turbo",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  fireworks: {
    name: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "accounts/fireworks/models/kimi-k2p6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "accounts/fireworks/routers/kimi-k2p5-turbo",
        name: "Kimi K2.5 Turbo Fire Pass",
        context: 256000,
        maxTokens: 256000,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  novita: {
    name: "Novita AI",
    baseUrl: "https://api.novita.ai/openai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "moonshotai/kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "minimax/minimax-m2.7",
        name: "MiniMax M2.7",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/glm-5",
        name: "GLM-5",
        context: 202752,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek/deepseek-v3-0324",
        name: "DeepSeek V3 0324",
        context: 163840,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek/deepseek-r1-0528",
        name: "DeepSeek R1 0528",
        context: 163840,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen/qwen3-235b-a22b-fp8",
        name: "Qwen3 235B A22B FP8",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  stepfun: {
    name: "StepFun",
    baseUrl: "https://api.stepfun.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "step-3.7-flash",
        name: "Step-3.7 Flash",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "step-3.5-flash",
        name: "Step-3.5 Flash",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  tencent: {
    name: "Tencent TokenHub",
    baseUrl: "https://tokenhub.tencentmaas.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "hy3",
        name: "Hy3",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "hy3-preview",
        name: "HunYuan3 Preview",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  volcengine: {
    name: "Volcengine (ByteDance Ark)",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "doubao-seed-code-preview-251028",
        name: "Doubao Seed Code Preview",
        context: 256000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "doubao-seed-1-8-251228",
        name: "Doubao Seed 1.8",
        context: 256000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        context: 256000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        context: 200000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "deepseek-v3-2-251201",
        name: "DeepSeek V3.2",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  byteplus: {
    name: "BytePlus (ByteDance Ark)",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/v3",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "seed-1-8-251228",
        name: "Doubao Seed 1.8",
        context: 256000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "kimi-k2-5-260127",
        name: "Kimi K2.5",
        context: 256000,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-4-7-251222",
        name: "GLM 4.7",
        context: 200000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  gmi: {
    name: "GMI",
    baseUrl: "https://api.gmi-serving.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "zai-org/GLM-5.1-FP8",
        name: "GLM 5.1 FP8",
        context: 202752,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        context: 163840,
        maxTokens: 65536,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "google/gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        context: 200000,
        maxTokens: 64000,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  kilocode: {
    name: "Kilo Code",
    baseUrl: "https://api.kilo.ai/api/gateway",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "kilo/auto",
        name: "Kilo Auto",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "google/gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
    ],
  },
  "opencode-go": {
    name: "OpenCode Go",
    baseUrl: "https://opencode.ai/zen/go/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        context: 202752,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 202752,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m3",
        name: "MiniMax M3",
        api: "anthropic-messages",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "minimax-m2.7",
        name: "MiniMax M2.7",
        api: "anthropic-messages",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m2.5",
        name: "MiniMax M2.5",
        api: "anthropic-messages",
        context: 204800,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k3",
        name: "Kimi K3",
        context: 1048576,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "qwen3.7-max",
        name: "Qwen3.7 Max",
        api: "anthropic-messages",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen3.7-plus",
        name: "Qwen3.7 Plus",
        api: "anthropic-messages",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus",
        api: "anthropic-messages",
        context: 1000000,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus",
        api: "anthropic-messages",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "mimo-v2.5",
        name: "MiMo V2.5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "mimo-v2.5-pro",
        name: "MiMo V2.5 Pro",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "mimo-v2-pro",
        name: "MiMo V2 Pro",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "mimo-v2-omni",
        name: "MiMo V2 Omni",
        context: 262144,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "audio"],
      },
      {
        id: "grok-4.5",
        name: "Grok 4.5",
        context: 500000,
        maxTokens: 500000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "hy3",
        name: "Hy3",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "hy3-preview",
        name: "Hy3 Preview",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "ollama-cloud": {
    name: "Ollama Cloud",
    baseUrl: "https://ollama-cloud.com/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "minimax-m2.7:cloud",
        name: "MiniMax M2.7 (Cloud)",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.2:cloud",
        name: "GLM-5.2 (Cloud)",
        context: 1000000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m3:cloud",
        name: "MiniMax M3 (Cloud)",
        context: 1000000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.1:cloud",
        name: "GLM-5.1 (Cloud)",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2.5:cloud",
        name: "Kimi K2.5 (Cloud)",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
} as const;
