export const gmiProvider = {
  name: "GMI",
  baseUrl: "https://api.gmi-serving.com/v1",
  api: "openai-completions",
  authType: "api_key",
  models: [
    {
      id: "zai-org/GLM-5.1-FP8",
      name: "GLM 5.1 FP8",
      context: 202752,
      maxTokens: 65536,
      reasoning: true,
      input: ["text"],
    },
    {
      id: "deepseek-ai/DeepSeek-V3.2",
      name: "DeepSeek V3.2",
      context: 163840,
      maxTokens: 65536,
      reasoning: false,
      input: ["text"],
    },
    {
      id: "moonshotai/Kimi-K2.5",
      name: "Kimi K2.5",
      context: 262144,
      maxTokens: 65536,
      reasoning: true,
      input: ["text", "image"],
    },
    {
      id: "google/gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      context: 1048576,
      maxTokens: 65536,
      reasoning: false,
      input: ["text", "image"],
    },
    {
      id: "anthropic/claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      context: 200000,
      maxTokens: 64000,
      reasoning: false,
      input: ["text", "image"],
    },
    {
      id: "openai/gpt-5.4",
      name: "GPT-5.4",
      context: 400000,
      maxTokens: 128000,
      reasoning: true,
      input: ["text", "image"],
    },
  ],
} as const;
