export const codingProviderCatalog = {
  groq: {
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "groq/compound",
        name: "Compound",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "groq/compound-mini",
        name: "Compound Mini",
        context: 131072,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "meta-llama/llama-4-scout-17b-16e-instruct",
        name: "Llama 4 Scout 17B",
        context: 131072,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-safeguard-20b",
        name: "Safety GPT OSS 20B",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "qwen/qwen3-32b",
        name: "Qwen3 32B",
        context: 131072,
        maxTokens: 40960,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        context: 128000,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        context: 32768,
        maxTokens: 16384,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "gemma-7b-it",
        name: "Gemma 7B",
        context: 32768,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  openrouter: {
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "anthropic/claude-opus-5-fast",
        name: "Claude Opus 5 (Fast)",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "anthropic/claude-opus-5",
        name: "Claude Opus 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "anthropic/claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-sonnet-5",
        name: "Claude Sonnet 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "anthropic/claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "google/gemini-3.6-flash",
        name: "Gemini 3.6 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "google/gemini-3.5-flash-lite",
        name: "Gemini 3.5 Flash Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "moonshotai/kimi-k3",
        name: "Kimi K3",
        context: 1048576,
        maxTokens: 1048576,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "openai/gpt-5.6-sol-pro",
        name: "GPT-5.6 Sol Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "openai/gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "openai/gpt-5.6-terra-pro",
        name: "GPT-5.6 Terra Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "openai/gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "openai/gpt-5.6-luna-pro",
        name: "GPT-5.6 Luna Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "x-ai/grok-4.5",
        name: "Grok 4.5",
        context: 500000,
        maxTokens: 500000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "meituan/longcat-2.0",
        name: "LongCat 2.0",
        context: 1048756,
        maxTokens: 262144,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "tencent/hy3",
        name: "Hy3",
        context: 262144,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-5.5",
        name: "GPT-5.5",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax/minimax-m3",
        name: "MiniMax M3",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "z-ai/glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "anthropic/claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "anthropic/claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-5.2",
        name: "GPT-5.2",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  opencode_zen: {
    name: "OpenCode Zen",
    baseUrl: "https://opencode.ai/zen/v1",
    api: "anthropic-messages",
    authType: "api_key",
    models: [
      {
        id: "claude-opus-5",
        name: "Claude Opus 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        context: 1048576,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-1",
        name: "Claude Opus 4.1",
        context: 200000,
        maxTokens: 32000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5",
        context: 1000000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-sonnet-4",
        name: "Claude Sonnet 4",
        context: 1000000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 1050000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 Nano",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        context: 128000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "pdf"],
      },
      {
        id: "gpt-5",
        name: "GPT-5",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5-codex",
        name: "GPT-5 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3.1-pro",
        name: "Gemini 3.1 Pro Preview",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video", "audio", "pdf"],
      },
      {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3.6-flash",
        name: "Gemini 3.6 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "gemini-3.5-flash-lite",
        name: "Gemini 3.5 Flash Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "laguna-s-2.1-free",
        name: "Laguna S 2.1 Free",
        context: 256000,
        maxTokens: 32000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "ling-3.0-flash-free",
        name: "Ling 3.0 Flash Free",
        context: 262144,
        maxTokens: 32768,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m3",
        name: "MiniMax M3",
        context: 512000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "minimax-m2.5",
        name: "MiniMax-M2.5",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        context: 1000000,
        maxTokens: 384000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-v4-flash-free",
        name: "DeepSeek V4 Flash Free",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "grok-4.5",
        name: "Grok 4.5",
        context: 500000,
        maxTokens: 500000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "grok-build-0.1",
        name: "Grok Build 0.1",
        context: 256000,
        maxTokens: 256000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "qwen3.5-plus",
        name: "Qwen3.5 Plus",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "video"],
      },
      {
        id: "kimi-k2.5",
        name: "Kimi K2.5",
        context: 262144,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "minimax-m2.7",
        name: "MiniMax M2.7",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 400000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gemini-3-flash",
        name: "Gemini 3 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "big-pickle",
        name: "Big Pickle",
        context: 200000,
        maxTokens: 32000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "mimo-v2.5-free",
        name: "MiMo V2.5 Free",
        context: 200000,
        maxTokens: 32000,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "hy3-free",
        name: "Hy3 Free",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "nemotron-3-ultra-free",
        name: "Nemotron 3 Ultra Free",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "north-mini-code-free",
        name: "North Mini Code Free",
        context: 256000,
        maxTokens: 64000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "z.ai": {
    name: "Z.AI (Zhipu)",
    baseUrl: "https://api.z.ai/api/paas/v4",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "glm-4.5-flash",
        name: "GLM-4.5 Flash",
        context: 131072,
        maxTokens: 98304,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.5v",
        name: "GLM-4.5V",
        context: 64000,
        maxTokens: 16384,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-4.6",
        name: "GLM-4.6",
        context: 204800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.7-flashx",
        name: "GLM-4.7 FlashX",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5",
        name: "GLM-5",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5-turbo",
        name: "GLM-5 Turbo",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-5v-turbo",
        name: "GLM-5V Turbo",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.5-air",
        name: "GLM-4.5 Air",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "glm-4.7-flash",
        name: "GLM-4.7 Flash",
        context: 128000,
        maxTokens: 8192,
        reasoning: false,
        input: ["text"],
      },
    ],
  },
  "z.ai-coding": {
    name: "Z.AI Coding Plan",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "glm-5.2",
        name: "GLM-5.2 (Coding)",
        context: 1000000,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1 (Coding)",
        context: 202800,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-5",
        name: "GLM-5 (Coding)",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-4.7",
        name: "GLM-4.7 (Coding)",
        context: 204800,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5 (Coding)",
        context: 128000,
        maxTokens: 8192,
        reasoning: true,
        input: ["text"],
        code: true,
      },
    ],
  },
  "openai-codex": {
    name: "OpenAI Codex (ChatGPT OAuth)",
    baseUrl: "https://chatgpt.com/backend-api",
    api: "openai-codex-responses",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthConfig: {
      clientId: "app_EMoamEEZ73f0CkXaXp7hrann",
      authorizeUrl: "https://auth.openai.com/oauth/authorize",
      tokenUrl: "https://auth.openai.com/oauth/token",
      scope: "openid profile email offline_access",
      callbackPort: 1455,
      callbackPath: "/auth/callback",
      authorizeParams: {
        id_token_add_organizations: "true",
        codex_cli_simplified_flow: "true",
        originator: "cybara",
      },
    },
    oauthLoginUrl: "https://chatgpt.com/",
    models: [
      {
        id: "gpt-5.6-sol",
        name: "GPT-5.6-Sol",
        context: 372000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-terra",
        name: "GPT-5.6-Terra",
        context: 372000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT-5.6-Luna",
        context: 372000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.5",
        name: "GPT-5.5",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.4",
        name: "GPT-5.4",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 Mini",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2-codex",
        name: "GPT-5.2 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        context: 128000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text"],
        code: true,
      },
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.1-codex",
        name: "GPT-5.1 Codex",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-mini",
        name: "GPT-5.1 Codex Mini",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
      {
        id: "gpt-5.1-codex-max",
        name: "GPT-5.1 Codex Max",
        context: 272000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
        code: true,
      },
    ],
  },
  chutes: {
    name: "Chutes",
    baseUrl: "https://llm.chutes.ai/v1",
    api: "openai-completions",
    authType: "api_key",
    oauthLoginUrl: "https://chutes.ai/app/api-keys",
    models: [
      {
        id: "Qwen/Qwen3-32B",
        name: "Qwen/Qwen3-32B",
        context: 40960,
        maxTokens: 40960,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "unsloth/Mistral-Nemo-Instruct-2407",
        name: "unsloth/Mistral-Nemo-Instruct-2407",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3-0324-TEE",
        name: "deepseek-ai/DeepSeek-V3-0324-TEE",
        context: 163840,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
        name: "Qwen/Qwen3-235B-A22B-Instruct-2507-TEE",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-120b-TEE",
        name: "openai/gpt-oss-120b-TEE",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "chutesai/Mistral-Small-3.1-24B-Instruct-2503",
        name: "chutesai/Mistral-Small-3.1-24B-Instruct-2503",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2-TEE",
        name: "deepseek-ai/DeepSeek-V3.2-TEE",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-4.7-TEE",
        name: "zai-org/GLM-4.7-TEE",
        context: 202752,
        maxTokens: 65535,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "moonshotai/Kimi-K2.5-TEE",
        name: "moonshotai/Kimi-K2.5-TEE",
        context: 262144,
        maxTokens: 65535,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "unsloth/gemma-3-27b-it",
        name: "unsloth/gemma-3-27b-it",
        context: 128000,
        maxTokens: 65536,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "XiaomiMiMo/MiMo-V2-Flash-TEE",
        name: "XiaomiMiMo/MiMo-V2-Flash-TEE",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "chutesai/Mistral-Small-3.2-24B-Instruct-2506",
        name: "chutesai/Mistral-Small-3.2-24B-Instruct-2506",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "deepseek-ai/DeepSeek-R1-0528-TEE",
        name: "deepseek-ai/DeepSeek-R1-0528-TEE",
        context: 163840,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-5-TEE",
        name: "zai-org/GLM-5-TEE",
        context: 202752,
        maxTokens: 65535,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-TEE",
        name: "deepseek-ai/DeepSeek-V3.1-TEE",
        context: 163840,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1-Terminus-TEE",
        name: "deepseek-ai/DeepSeek-V3.1-Terminus-TEE",
        context: 163840,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "unsloth/gemma-3-4b-it",
        name: "unsloth/gemma-3-4b-it",
        context: 96000,
        maxTokens: 96000,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "MiniMaxAI/MiniMax-M2.5-TEE",
        name: "MiniMaxAI/MiniMax-M2.5-TEE",
        context: 196608,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "tngtech/DeepSeek-TNG-R1T2-Chimera",
        name: "tngtech/DeepSeek-TNG-R1T2-Chimera",
        context: 163840,
        maxTokens: 163840,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3-Coder-Next-TEE",
        name: "Qwen/Qwen3-Coder-Next-TEE",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "NousResearch/Hermes-4-405B-FP8-TEE",
        name: "NousResearch/Hermes-4-405B-FP8-TEE",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-V3",
        name: "deepseek-ai/DeepSeek-V3",
        context: 163840,
        maxTokens: 163840,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "openai/gpt-oss-20b",
        name: "openai/gpt-oss-20b",
        context: 131072,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "unsloth/Llama-3.2-3B-Instruct",
        name: "unsloth/Llama-3.2-3B-Instruct",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "unsloth/Mistral-Small-24B-Instruct-2501",
        name: "unsloth/Mistral-Small-24B-Instruct-2501",
        context: 32768,
        maxTokens: 32768,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "zai-org/GLM-4.7-FP8",
        name: "zai-org/GLM-4.7-FP8",
        context: 202752,
        maxTokens: 65535,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-4.6-TEE",
        name: "zai-org/GLM-4.6-TEE",
        context: 202752,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3.5-397B-A17B-TEE",
        name: "Qwen/Qwen3.5-397B-A17B-TEE",
        context: 262144,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen/Qwen2.5-72B-Instruct",
        context: 32768,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "NousResearch/DeepHermes-3-Mistral-24B-Preview",
        name: "NousResearch/DeepHermes-3-Mistral-24B-Preview",
        context: 32768,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-4.6-FP8",
        name: "zai-org/GLM-4.6-FP8",
        context: 202752,
        maxTokens: 65535,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        name: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        context: 131072,
        maxTokens: 131072,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "tngtech/R1T2-Chimera-Speed",
        name: "tngtech/R1T2-Chimera-Speed",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "zai-org/GLM-4.6V",
        name: "zai-org/GLM-4.6V",
        context: 131072,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "Qwen/Qwen2.5-VL-32B-Instruct",
        name: "Qwen/Qwen2.5-VL-32B-Instruct",
        context: 16384,
        maxTokens: 16384,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "Qwen/Qwen3-VL-235B-A22B-Instruct",
        name: "Qwen/Qwen3-VL-235B-A22B-Instruct",
        context: 262144,
        maxTokens: 262144,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "Qwen/Qwen3-14B",
        name: "Qwen/Qwen3-14B",
        context: 40960,
        maxTokens: 40960,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen2.5-Coder-32B-Instruct",
        name: "Qwen/Qwen2.5-Coder-32B-Instruct",
        context: 32768,
        maxTokens: 32768,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3-30B-A3B",
        name: "Qwen/Qwen3-30B-A3B",
        context: 40960,
        maxTokens: 40960,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "unsloth/gemma-3-12b-it",
        name: "unsloth/gemma-3-12b-it",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text", "image"],
      },
      {
        id: "unsloth/Llama-3.2-1B-Instruct",
        name: "unsloth/Llama-3.2-1B-Instruct",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE",
        name: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16-TEE",
        context: 128000,
        maxTokens: 4096,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "NousResearch/Hermes-4-14B",
        name: "NousResearch/Hermes-4-14B",
        context: 40960,
        maxTokens: 40960,
        reasoning: true,
        input: ["text"],
      },
      {
        id: "Qwen/Qwen3Guard-Gen-0.6B",
        name: "Qwen/Qwen3Guard-Gen-0.6B",
        context: 128000,
        maxTokens: 4096,
        reasoning: false,
        input: ["text"],
      },
      {
        id: "rednote-hilab/dots.ocr",
        name: "rednote-hilab/dots.ocr",
        context: 131072,
        maxTokens: 131072,
        reasoning: false,
        input: ["text", "image"],
      },
    ],
  },
  "vercel-ai-gateway": {
    name: "Vercel AI Gateway",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    api: "openai-completions",
    authType: "api_key",
    models: [
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        context: 1000000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4",
        name: "GPT-5.4",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "openai/gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        context: 200000,
        maxTokens: 128000,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "moonshotai/kimi-k2.6",
        name: "Kimi K2.6",
        context: 262144,
        maxTokens: 262144,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5",
        context: 200000,
        maxTokens: 81920,
        reasoning: true,
        input: ["text", "image"],
      },
      {
        id: "gpt-5.2",
        name: "GPT-5.2",
        context: 200000,
        maxTokens: 100000,
        reasoning: true,
        input: ["text"],
      },
    ],
  },
  "google-gemini-cli": {
    name: "Google Gemini CLI",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    api: "google-generative-ai",
    authType: "oauth",
    oauthFlow: "redirect" as const,
    oauthConfig: {
      authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
      tokenUrl: "https://oauth2.googleapis.com/token",
      scope:
        "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
      callbackPort: 8085,
      callbackPath: "/oauth2callback",
    },
    oauthLoginUrl: "https://github.com/google-gemini/gemini-cli",
    models: [
      {
        id: "gemini-3.6-flash",
        name: "Gemini 3.6 Flash",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "gemini-3.5-flash-lite",
        name: "Gemini 3.5 Flash Lite",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video", "pdf"],
      },
      {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro",
        context: 1048576,
        maxTokens: 65536,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        context: 1048576,
        maxTokens: 32768,
        reasoning: true,
        input: ["text", "image", "audio", "video"],
      },
      {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash",
        context: 1048576,
        maxTokens: 8192,
        reasoning: false,
        input: ["text", "image", "audio", "video"],
      },
    ],
  },
  "copilot-proxy": {
    name: "Copilot Proxy",
    baseUrl: "http://localhost:1234/v1",
    api: "openai-completions",
    authType: "none",
    models: [],
  },
} as const;
