import { Platform, StyleSheet } from "react-native";
import { colors, radius, spacing, typography } from "../theme/liquidGlass";

export function createDashboardChatStyles() {
  return {
    messageBubble: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      flexShrink: 1,
      gap: spacing.xs,
      maxWidth: "86%",
      padding: spacing.md,
    },
    agentMessageRow: {
      gap: spacing.xs,
      width: "100%",
    },
    userMessageBubble: {
      backgroundColor: colors.surfaceLift,
    },
    messageThinking: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontStyle: "italic",
      lineHeight: 18,
    },
    messageText: {
      color: colors.text,
      fontSize: typography.body,
      lineHeight: 22,
    },
    messageTime: {
      color: colors.textDim,
      fontSize: typography.tiny,
      marginTop: 2,
    },
    messageTimeUser: {
      textAlign: "right",
    },
    messageActionsRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.xs,
      marginTop: 2,
    },
    messageActionsRowEnd: {
      justifyContent: "flex-end",
    },
    messageActionButton: {
      borderRadius: 6,
      padding: 4,
    },
    userMessageColumn: {
      alignItems: "flex-end",
      flexShrink: 1,
    },
    messageContent: {
      gap: spacing.sm,
    },
    chatImageList: {
      gap: spacing.sm,
    },
    chatImageWrapper: {
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      overflow: "hidden",
      width: "100%",
    },
    chatImage: {
      backgroundColor: colors.scrim,
      width: "100%",
    },
    chatImagePreviewBackdrop: {
      alignItems: "center",
      backgroundColor: "rgba(0, 0, 0, 0.94)",
      flex: 1,
      justifyContent: "center",
      padding: spacing.md,
    },
    chatImagePreview: {
      height: "100%",
      width: "100%",
    },
    chatImagePreviewClose: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderColor: colors.borderStrong,
      borderRadius: 22,
      borderWidth: 1,
      height: 44,
      justifyContent: "center",
      position: "absolute",
      right: spacing.lg,
      top: spacing.xxl,
      width: 44,
    },
    mobilePlanCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      marginBottom: spacing.sm,
      overflow: "hidden",
    },
    mobilePlanHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    mobilePlanIcon: {
      alignItems: "center",
      height: 22,
      justifyContent: "center",
      width: 22,
    },
    mobilePlanHeaderText: {
      flex: 1,
      gap: 2,
    },
    mobilePlanTitleRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    mobilePlanTitle: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
    },
    mobilePlanProgressText: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "700",
    },
    mobilePlanCurrentTask: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      lineHeight: 16,
    },
    mobilePlanProgressTrack: {
      backgroundColor: colors.border,
      height: StyleSheet.hairlineWidth,
    },
    mobilePlanProgressFill: {
      backgroundColor: colors.textMuted,
      height: StyleSheet.hairlineWidth,
    },
    mobilePlanItems: {
      borderTopColor: colors.border,
      borderTopWidth: StyleSheet.hairlineWidth,
      gap: spacing.xs,
      padding: spacing.md,
    },
    mobilePlanItem: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.sm,
    },
    mobilePlanItemIcon: {
      alignItems: "center",
      height: 18,
      justifyContent: "center",
      width: 18,
    },
    mobilePlanPendingDot: {
      backgroundColor: colors.textMuted,
      borderRadius: 3,
      height: 6,
      opacity: 0.8,
      width: 6,
    },
    mobilePlanItemText: {
      color: colors.text,
      flex: 1,
      fontSize: typography.label,
      lineHeight: 18,
    },
    mobilePlanItemTextDone: {
      color: colors.textMuted,
      textDecorationLine: "line-through",
    },
    mobilePlanPriority: {
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: colors.textMuted,
      fontSize: typography.tiny,
      overflow: "hidden",
      paddingHorizontal: 6,
      paddingVertical: 2,
      textTransform: "capitalize",
    },
    codeBlock: {
      backgroundColor: colors.scrim,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: 1,
      overflow: "hidden",
    },
    codeHeader: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.xs,
      minHeight: 30,
      paddingHorizontal: spacing.sm,
    },
    codeLanguage: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    codeLineCount: {
      color: colors.textDim,
      flex: 1,
      fontSize: 10,
    },
    codeCopyButton: {
      alignItems: "center",
      height: 28,
      justifyContent: "center",
      width: 28,
    },
    codeScroll: {
      flexGrow: 0,
      flexShrink: 1,
    },
    codeText: {
      color: colors.text,
      fontSize: 12,
      lineHeight: 17,
      padding: spacing.sm,
    },
    codeTextMonospace: {
      fontFamily: Platform.select({
        ios: "Menlo",
        android: "monospace",
        default: "monospace",
      }),
    },
    mdBlocks: {
      gap: spacing.sm,
    },
    mdH1: {
      color: colors.text,
      fontSize: typography.title,
      fontWeight: "800",
      lineHeight: 30,
      marginTop: spacing.xs,
    },
    mdH2: {
      color: colors.text,
      fontSize: typography.heading,
      fontWeight: "800",
      lineHeight: 26,
      marginTop: spacing.xs,
    },
    mdH3: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
      lineHeight: 22,
    },
    mdParagraph: {
      color: colors.text,
      fontSize: typography.body,
      lineHeight: 22,
    },
    mdBold: {
      fontWeight: "800",
    },
    mdItalic: {
      fontStyle: "italic",
    },
    mdStrike: {
      textDecorationLine: "line-through",
    },
    mdLink: {
      color: colors.cyan,
      textDecorationLine: "underline",
    },
    mdInlineCode: {
      backgroundColor: colors.scrim,
      color: colors.text,
      fontFamily: Platform.select({
        ios: "Menlo",
        android: "monospace",
        default: "monospace",
      }),
      fontSize: 13,
    },
    mdListRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.xs,
      paddingLeft: spacing.xs,
    },
    mdListMarker: {
      color: colors.textMuted,
      fontSize: typography.body,
      lineHeight: 22,
      minWidth: 18,
    },
    mdTaskCheckbox: {
      alignItems: "center",
      borderColor: colors.textMuted,
      borderRadius: 4,
      borderWidth: 1,
      height: 16,
      justifyContent: "center",
      marginTop: 3,
      width: 16,
    },
    mdTaskCheckboxChecked: {
      backgroundColor: colors.cyan,
      borderColor: colors.cyan,
    },
    mdListText: {
      color: colors.text,
      flex: 1,
      fontSize: typography.body,
      lineHeight: 22,
    },
    mdQuote: {
      borderLeftColor: colors.border,
      borderLeftWidth: 3,
      paddingLeft: spacing.sm,
    },
    mdQuoteText: {
      color: colors.textMuted,
      fontSize: typography.body,
      fontStyle: "italic",
      lineHeight: 22,
    },
    mdRule: {
      backgroundColor: colors.border,
      height: StyleSheet.hairlineWidth,
      marginVertical: spacing.xs,
    },
    mdTable: {
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: 1,
      overflow: "hidden",
    },
    mdTableRow: {
      borderTopColor: colors.border,
      borderTopWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
    },
    mdTableHeaderRow: {
      backgroundColor: colors.surfaceLift,
      flexDirection: "row",
    },
    mdTableCell: {
      borderLeftColor: colors.border,
      borderLeftWidth: StyleSheet.hairlineWidth,
      flex: 1,
      minWidth: 90,
      paddingHorizontal: spacing.sm,
      paddingVertical: 6,
    },
    mdTableCellText: {
      color: colors.text,
      fontSize: 13,
      lineHeight: 18,
    },
    mdTableHeaderText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "800",
      lineHeight: 18,
    },
    workTimeline: {
      gap: spacing.xs,
      marginBottom: spacing.xs,
    },
    workTimelineHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: 3,
      minHeight: 24,
      paddingHorizontal: 2,
    },
    workedForText: {
      color: colors.textDim,
      fontSize: typography.label,
    },
    messageActivityList: {
      gap: spacing.xs,
      paddingHorizontal: 2,
    },
    messageActivityRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.xs,
    },
    messageActivityIcon: {
      alignItems: "center",
      height: 16,
      justifyContent: "center",
      marginTop: 1,
      width: 16,
    },
    messageActivityDot: {
      backgroundColor: colors.textMuted,
      borderRadius: 3,
      height: 6,
      opacity: 0.75,
      width: 6,
    },
    messageAuthorRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      marginBottom: 4,
    },
    messageAuthorText: {
      color: colors.textMuted,
      fontSize: typography.label,
      lineHeight: 14,
    },
    messageActivityText: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.label,
      lineHeight: 18,
    },
    messageThoughtText: {
      color: colors.textMuted,
    },
    messageActivityGroupLabel: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.label,
      fontWeight: "600",
      lineHeight: 18,
    },
    messageActivityGroupItems: {
      borderLeftColor: colors.border,
      borderLeftWidth: 1,
      gap: spacing.xs,
      marginLeft: 6,
      paddingLeft: spacing.sm,
    },
    mobileFileChangesCard: {
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing.xs,
      padding: spacing.sm,
    },
    mobileFileChangesHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.xs,
    },
    mobileFileChangesTitle: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.label,
      fontWeight: "700",
    },
    mobileFileChangesAdded: {
      color: colors.green,
      fontSize: typography.label,
      fontWeight: "700",
    },
    mobileFileChangesRemoved: {
      color: colors.red,
      fontSize: typography.label,
      fontWeight: "700",
    },
    mobileFileChangeRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    mobileFileChangeNameColumn: {
      flex: 1,
      minWidth: 0,
    },
    mobileFileChangeName: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "700",
      lineHeight: 18,
    },
    mobileFileChangePath: {
      color: colors.textDim,
      fontSize: 11,
      lineHeight: 15,
    },
    mobileFileChangeCounts: {
      flexDirection: "row",
      gap: spacing.xs,
    },
    loadingRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    typingRow: {
      alignItems: "center",
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      padding: spacing.md,
    },
    pendingQueue: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing.sm,
      padding: spacing.md,
    },
    pendingQueueTitle: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontWeight: "800",
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    pendingQueueItem: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderRadius: radius.sm,
      flexDirection: "row",
      gap: spacing.sm,
      padding: spacing.sm,
    },
    pendingQueueText: {
      flex: 1,
      gap: 3,
    },
    pendingQueueMeta: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "700",
    },
    pendingQueueContent: {
      color: colors.text,
      fontSize: typography.label,
      lineHeight: 18,
    },
    pendingQueueActions: {
      alignItems: "flex-end",
      gap: spacing.xs,
    },
    pendingOrderControls: {
      flexDirection: "row",
      gap: 4,
    },
    pendingOrderButton: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      height: 28,
      justifyContent: "center",
      width: 28,
    },
    pendingOrderButtonDisabled: {
      opacity: 0.35,
    },
    pendingSteerButton: {
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      minWidth: 72,
      paddingHorizontal: spacing.sm,
      paddingVertical: 7,
    },
    pendingSteerText: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
    },
    pendingEditOverlay: {
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.56)",
      flex: 1,
      justifyContent: "center",
      padding: spacing.lg,
    },
    pendingEditCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      gap: spacing.md,
      padding: spacing.lg,
      width: "100%",
    },
    pendingEditTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    pendingEditInput: {
      backgroundColor: colors.inset,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      color: colors.text,
      fontSize: typography.body,
      minHeight: 110,
      padding: spacing.md,
      textAlignVertical: "top",
    },
    pendingEditActions: {
      flexDirection: "row",
      gap: spacing.sm,
      justifyContent: "flex-end",
    },
    pendingEditCancelButton: {
      alignItems: "center",
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      minWidth: 86,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    pendingEditCancelText: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
    },
    pendingEditSaveButton: {
      alignItems: "center",
      borderRadius: radius.md,
      minWidth: 86,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    pendingEditSaveText: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
    },
    chatSettingsOverlay: {
      backgroundColor: "rgba(0,0,0,0.48)",
      flex: 1,
      justifyContent: "flex-end",
    },
    chatSettingsBackdrop: {
      ...StyleSheet.absoluteFill,
    },
    chatSettingsSheetFrame: {
      marginHorizontal: spacing.md,
      maxHeight: "88%",
    },
    chatSettingsSheet: {
      borderRadius: radius.xl,
      height: "100%",
      maxHeight: "100%",
    },
    chatSettingsSheetContent: {
      flex: 1,
      gap: spacing.sm,
      paddingBottom: spacing.xl,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.sm,
    },
    chatSettingsDragHandle: {
      gap: spacing.sm,
      paddingBottom: spacing.xs,
    },
    chatSettingsGrabber: {
      alignSelf: "center",
      backgroundColor: colors.textDim,
      borderRadius: 999,
      height: 4,
      opacity: 0.5,
      width: 42,
    },
    chatSettingsHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    chatSettingsTitleWrap: {
      flex: 1,
      gap: 3,
      minWidth: 0,
    },
    chatSettingsTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "900",
      lineHeight: 20,
    },
    chatSettingsSubtitle: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      lineHeight: 16,
    },
    chatSettingsCloseButton: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderColor: colors.border,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    chatSettingsScroll: {
      flex: 1,
    },
    chatSettingsScrollContent: {
      gap: spacing.md,
      paddingBottom: spacing.xl,
    },
    chatSettingsInfoGroup: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: "hidden",
    },
    chatSettingsInfoRow: {
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.md,
      minHeight: 58,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    chatSettingsInfoIcon: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderRadius: radius.sm,
      height: 32,
      justifyContent: "center",
      marginTop: 2,
      width: 32,
    },
    chatSettingsInfoText: {
      flex: 1,
      gap: 2,
      minWidth: 0,
    },
    chatSettingsInfoLabel: {
      color: colors.textDim,
      fontSize: typography.tiny,
      fontWeight: "900",
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    chatSettingsInfoValue: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
      lineHeight: 18,
    },
    chatSettingsInfoDetail: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      lineHeight: 16,
    },
    chatSettingsActionsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    chatSettingsActionButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      flexBasis: "48%",
      flexDirection: "row",
      flexGrow: 1,
      gap: spacing.xs,
      minHeight: 46,
      minWidth: 132,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    chatSettingsActionButtonDestructive: {
      backgroundColor: colors.softRed,
      borderColor: colors.softRedBorder,
    },
    chatSettingsActionButtonDisabled: {
      opacity: 0.58,
    },
    chatSettingsActionText: {
      color: colors.text,
      flex: 1,
      fontSize: typography.label,
      fontWeight: "800",
    },
    chatSettingsActionTextDestructive: {
      color: colors.red,
    },
  } as const;
}
