import { Platform, StyleSheet } from "react-native";
import { colors, radius, spacing, subscribeColors, typography } from "../theme/liquidGlass";
import {
  MOBILE_CHAT_CHROME,
  MOBILE_CHAT_COMPOSER,
  MOBILE_HOME_CHROME,
  MOBILE_MAIN_TAB_CHROME,
  MOBILE_NAV_CHROME,
} from "../lib/dashboard";

const makeStyles = () =>
  StyleSheet.create({
    screen: {
      flex: 1,
    },
    scrollArea: {
      flex: 1,
    },
    content: {
      gap: spacing.md,
      paddingBottom: MOBILE_NAV_CHROME.height + spacing.lg,
    },
    header: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.md,
      paddingHorizontal: spacing.lg,
    },
    brandWrap: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      gap: spacing.md,
    },
    logoMark: {
      alignItems: "center",
      backgroundColor: colors.softCyan,
      borderColor: colors.softCyanBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      height: 50,
      justifyContent: "center",
      overflow: "hidden",
      width: 50,
    },
    logoImage: {
      height: 40,
      width: 40,
    },
    backButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.borderStrong,
      borderRadius: radius.md,
      borderWidth: 1,
      height: 50,
      justifyContent: "center",
      width: 50,
    },
    headerText: {
      flex: 1,
      gap: 2,
    },
    title: {
      color: colors.text,
      fontSize: 30,
      fontWeight: "900",
    },
    detailTitle: {
      fontSize: 22,
      lineHeight: 26,
    },
    headerDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
      lineHeight: 17,
    },
    iconButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.borderStrong,
      borderRadius: 28,
      borderWidth: 1,
      height: 48,
      justifyContent: "center",
      width: 48,
    },
    iconButtonDisabled: {
      opacity: 0.55,
    },
    connectionRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    liveDot: {
      borderRadius: 7,
      height: 14,
      shadowColor: colors.green,
      shadowOpacity: 0.55,
      shadowRadius: 8,
      width: 14,
    },
    connectionText: {
      fontSize: typography.body,
      fontWeight: "700",
    },
    gatewayTop: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.md,
      justifyContent: "space-between",
    },
    gatewayIdentity: {
      flex: 1,
      gap: 4,
    },
    gatewayName: {
      color: colors.text,
      fontSize: 24,
      fontWeight: "900",
    },
    gatewayMeta: {
      color: colors.textMuted,
      fontSize: typography.label,
    },
    settingsGatewayCard: {
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      gap: spacing.md,
      padding: spacing.md,
    },
    gatewayDetailGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    gatewayDetailPill: {
      backgroundColor: colors.inset,
      borderRadius: radius.sm,
      flexBasis: "48%",
      flexGrow: 1,
      gap: 3,
      minHeight: 58,
      minWidth: 132,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    gatewayDetailLabel: {
      color: colors.textDim,
      fontSize: typography.tiny,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    gatewayDetailValue: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
    },
    errorText: {
      color: colors.red,
      fontSize: typography.label,
      lineHeight: 18,
    },
    overviewInset: {
      gap: spacing.sm,
      paddingHorizontal: MOBILE_HOME_CHROME.managementGridEdgeToEdge ? 0 : spacing.lg,
    },
    moduleGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    moduleTile: {
      backgroundColor: colors.surface,
      borderColor: colors.borderStrong,
      borderRadius: radius.lg,
      borderWidth: 1,
      flexBasis: "48%",
      flexGrow: 1,
      gap: spacing.sm,
      minHeight: 108,
      padding: spacing.md,
    },
    moduleIcon: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderRadius: radius.md,
      height: 38,
      justifyContent: "center",
      width: 38,
    },
    moduleText: {
      flex: 1,
      justifyContent: "flex-end",
    },
    moduleTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    moduleDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
      marginTop: 3,
    },
    monitorTile: {
      alignItems: "center",
      flexBasis: "100%",
      flexDirection: "row",
      minHeight: 72,
    },
    monitorTilePrimary: {
      backgroundColor: colors.surface,
      minHeight: 78,
    },
    monitorText: {
      flex: 1,
    },
    activityPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.borderStrong,
      gap: spacing.sm,
    },
    panelHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    panelHeaderTitle: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    panelTitle: {
      color: colors.text,
      fontSize: typography.heading,
      fontWeight: "800",
    },
    smallButton: {
      backgroundColor: colors.inset,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    smallButtonText: {
      fontSize: typography.label,
      fontWeight: "800",
    },
    newChatButton: {
      alignItems: "center",
      borderRadius: radius.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 42,
      paddingHorizontal: spacing.md,
      paddingVertical: 8,
    },
    newChatButtonPressed: {
      backgroundColor: colors.insetStrong,
    },
    newChatIcon: {
      alignItems: "center",
      borderRadius: 11,
      height: 22,
      justifyContent: "center",
      width: 22,
    },
    newChatButtonText: {
      fontSize: typography.label,
      fontWeight: "900",
    },
    logPageFooter: {
      alignItems: "center",
      borderTopColor: colors.border,
      borderTopWidth: 1,
      gap: spacing.sm,
      paddingTop: spacing.md,
    },
    loadMoreButton: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderColor: colors.borderStrong,
      borderRadius: radius.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      justifyContent: "center",
      minHeight: 44,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.sm,
      width: "100%",
    },
    loadMoreButtonDisabled: {
      opacity: 0.65,
    },
    loadMoreButtonText: {
      color: colors.blueText,
      fontSize: typography.body,
      fontWeight: "900",
    },
    activityRow: {
      alignItems: "center",
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 62,
    },
    activityDot: {
      borderRadius: 6,
      height: 12,
      width: 12,
    },
    activityIcon: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderRadius: 22,
      height: 44,
      justifyContent: "center",
      width: 44,
    },
    activityText: {
      flex: 1,
      gap: 3,
    },
    activityTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    activityDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
    },
    statePill: {
      borderRadius: radius.md,
      borderWidth: 1,
      paddingHorizontal: spacing.md,
      paddingVertical: 5,
    },
    stateText: {
      fontSize: typography.label,
      fontWeight: "800",
    },
    detailPanel: {
      gap: spacing.md,
    },
    mainTabPanel: {
      borderLeftWidth: 0,
      borderRadius: MOBILE_MAIN_TAB_CHROME.panelRadius,
      borderRightWidth: 0,
    },
    settingsRootContent: {
      gap: 0,
      paddingHorizontal: 0,
    },
    settingsNativePage: {
      gap: spacing.lg,
    },
    settingsSection: {
      gap: spacing.xs,
      paddingHorizontal: spacing.lg,
    },
    settingsSectionHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 24,
      paddingHorizontal: spacing.sm,
    },
    settingsSectionTitle: {
      color: colors.textDim,
      fontSize: typography.tiny,
      fontWeight: "800",
      letterSpacing: 0,
      textTransform: "uppercase",
    },
    settingsGroup: {
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: "hidden",
    },
    settingsNavigationRow: {
      alignItems: "center",
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.md,
      minHeight: 58,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    settingsNavigationIcon: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderRadius: radius.sm,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    metricMicroGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    itemHero: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.md,
      padding: spacing.md,
    },
    itemHeroText: {
      flex: 1,
      gap: 3,
    },
    itemTitle: {
      color: colors.text,
      fontSize: typography.heading,
      fontWeight: "900",
    },
    itemDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
      lineHeight: 18,
    },
    infoSection: {
      gap: spacing.sm,
    },
    infoSectionTitle: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontWeight: "700",
      letterSpacing: 0.4,
      marginLeft: spacing.xs,
      textTransform: "uppercase",
    },
    infoCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: "hidden",
    },
    infoRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.md,
      justifyContent: "space-between",
      minHeight: 44,
      paddingHorizontal: spacing.md,
      paddingVertical: 11,
    },
    infoRowDivider: {
      borderTopColor: colors.border,
      borderTopWidth: StyleSheet.hairlineWidth,
    },
    infoLabel: {
      color: colors.textMuted,
      flexShrink: 0,
      fontSize: typography.body,
      maxWidth: "42%",
    },
    infoValue: {
      color: colors.text,
      flex: 1,
      fontSize: typography.body,
      fontWeight: "600",
      textAlign: "right",
    },
    chatShell: {
      flex: 1,
      position: "relative",
    },
    chatScroll: {
      flex: 1,
    },
    chatContent: {
      gap: spacing.sm,
      paddingBottom:
        MOBILE_CHAT_CHROME.composerReservedBottom + MOBILE_CHAT_COMPOSER.maxHeight + spacing.xl,
      paddingHorizontal: spacing.lg,
    },
    chatMessageRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.sm,
    },
    chatMessageRowUser: {
      flexDirection: "row-reverse",
    },
    chatAvatar: {
      alignItems: "center",
      borderRadius: 16,
      height: 32,
      justifyContent: "center",
      marginTop: 2,
      width: 32,
    },
    messageBubble: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      flexShrink: 1,
      gap: spacing.xs,
      maxWidth: "86%",
      padding: spacing.md,
    },
    assistantMessageBubble: {
      maxWidth: "92%",
    },
    userMessageBubble: {
      backgroundColor: colors.surfaceLift,
    },
    messageThinking: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontStyle: "italic",
      lineHeight: 18,
    },
    messageText: {
      color: colors.text,
      fontSize: typography.body,
      lineHeight: 22,
    },
    messageTime: {
      color: colors.textDim,
      fontSize: typography.tiny,
      marginTop: 2,
    },
    messageTimeUser: {
      textAlign: "right",
    },
    messageContent: {
      gap: spacing.sm,
    },
    codeBlock: {
      backgroundColor: colors.scrim,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: 1,
      overflow: "hidden",
    },
    codeHeader: {
      backgroundColor: colors.surfaceLift,
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "900",
      paddingHorizontal: spacing.sm,
      paddingVertical: 5,
      textTransform: "uppercase",
    },
    codeText: {
      color: colors.text,
      fontSize: 12,
      lineHeight: 17,
      padding: spacing.sm,
    },
    codeTextMonospace: {
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    workTimeline: {
      gap: spacing.xs,
      marginBottom: spacing.xs,
    },
    workedForText: {
      color: colors.textDim,
      fontSize: typography.label,
      paddingHorizontal: 2,
    },
    messageActivityList: {
      gap: spacing.xs,
      paddingHorizontal: 2,
    },
    messageActivityRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.xs,
    },
    messageActivityIcon: {
      alignItems: "center",
      height: 16,
      justifyContent: "center",
      marginTop: 1,
      width: 16,
    },
    messageActivityText: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.label,
      lineHeight: 18,
    },
    messageThoughtText: {
      color: colors.text,
    },
    loadingRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    typingRow: {
      alignItems: "center",
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      padding: spacing.md,
    },
    composer: {
      alignItems: "flex-end",
      backgroundColor: colors.surfaceLift,
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 50,
      paddingHorizontal: spacing.sm,
      paddingVertical: 6,
    },
    chatComposerBar: {
      bottom: MOBILE_CHAT_CHROME.composerReservedBottom + MOBILE_CHAT_CHROME.composerGapToNav,
      left: 0,
      minHeight: MOBILE_CHAT_CHROME.composerHeight,
      position: "absolute",
      right: 0,
    },
    chatComposerContent: {
      justifyContent: "center",
      paddingHorizontal: spacing.sm,
      paddingVertical: spacing.sm,
    },
    composerInput: {
      color: colors.text,
      flex: 1,
      fontSize: typography.body,
      includeFontPadding: false,
      lineHeight: 20,
      maxHeight: MOBILE_CHAT_COMPOSER.maxHeight,
      minHeight: MOBILE_CHAT_COMPOSER.minHeight,
      paddingHorizontal: spacing.sm,
      paddingTop: Platform.OS === "ios" ? 10 : 8,
      paddingBottom: Platform.OS === "ios" ? 8 : 7,
    },
    sendButton: {
      alignItems: "center",
      borderRadius: radius.md,
      height: MOBILE_CHAT_COMPOSER.minHeight,
      justifyContent: "center",
      width: MOBILE_CHAT_COMPOSER.minHeight,
    },
    accentGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
      padding: spacing.md,
    },
    accentSwatch: {
      alignItems: "center",
      backgroundColor: colors.inset,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      flexBasis: "30%",
      flexDirection: "row",
      flexGrow: 1,
      gap: spacing.xs,
      minHeight: 44,
      minWidth: 86,
      paddingHorizontal: spacing.sm,
    },
    accentSwatchDot: {
      borderRadius: 8,
      height: 16,
      shadowOpacity: 0.42,
      shadowRadius: 8,
      width: 16,
    },
    accentSwatchDotActive: {
      height: 18,
      width: 18,
    },
    accentSwatchLabel: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.tiny,
      fontWeight: "800",
      textTransform: "capitalize",
    },
    settingsForm: {
      gap: spacing.md,
    },
    settingsField: {
      gap: spacing.xs,
    },
    settingsSegmentField: {
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
    },
    settingsMenuRow: {
      alignItems: "center",
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.md,
      justifyContent: "space-between",
      minHeight: 48,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    settingsMenuLabel: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "600",
    },
    settingsMenuValueWrap: {
      alignItems: "center",
      flexDirection: "row",
      flexShrink: 1,
      gap: spacing.xs,
    },
    settingsMenuValue: {
      color: colors.textMuted,
      flexShrink: 1,
      fontSize: typography.body,
    },
    menuBackdrop: {
      backgroundColor: colors.scrim,
      flex: 1,
      justifyContent: "flex-end",
    },
    menuSheet: {
      backgroundColor: colors.backgroundLift,
      borderTopLeftRadius: radius.lg,
      borderTopRightRadius: radius.lg,
      gap: spacing.xs,
      paddingBottom: spacing.xl,
      paddingHorizontal: spacing.md,
      paddingTop: spacing.lg,
    },
    menuSheetTitle: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontWeight: "700",
      letterSpacing: 0.4,
      marginBottom: spacing.xs,
      textTransform: "uppercase",
    },
    menuSheetRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 48,
      paddingHorizontal: spacing.sm,
    },
    menuSheetRowText: {
      color: colors.text,
      fontSize: typography.body,
    },
    settingsFieldLabel: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    settingsInput: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      color: colors.text,
      fontSize: typography.body,
      minHeight: 48,
      paddingHorizontal: spacing.md,
      paddingVertical: Platform.OS === "ios" ? 12 : 8,
    },
    settingsTextArea: {
      lineHeight: 20,
      minHeight: 140,
    },
    settingsFieldHelp: {
      color: colors.textDim,
      fontSize: typography.tiny,
      lineHeight: 16,
    },
    settingsInfoBox: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing.sm,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
    },
    settingsInfoHeader: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.xs,
    },
    settingsInfoTitle: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "900",
    },
    settingsInfoText: {
      color: colors.textMuted,
      fontSize: typography.label,
      lineHeight: 18,
    },
    settingsInfoCode: {
      color: colors.text,
      fontFamily: Platform.select({ ios: "Menlo", default: "monospace" }),
      fontSize: typography.title,
      fontWeight: "900",
      letterSpacing: 2,
    },
    routerSummaryBox: {
      gap: spacing.xs,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
    },
    routerSummaryRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      gap: spacing.md,
    },
    routerSummaryLabel: {
      color: colors.textMuted,
      flex: 1,
      fontSize: typography.label,
    },
    routerSummaryValue: {
      color: colors.text,
      fontSize: typography.label,
      fontWeight: "800",
      textTransform: "capitalize",
    },
    settingsChipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    settingsSegmentedControl: {
      backgroundColor: colors.inset,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: StyleSheet.hairlineWidth,
      flexWrap: "nowrap",
      gap: 2,
      padding: 2,
    },
    settingsChip: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.sm,
      borderWidth: 1,
      minHeight: 44,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
    },
    settingsSegment: {
      borderRadius: 8,
      borderWidth: 0,
      flex: 1,
      justifyContent: "center",
      minHeight: 44,
      minWidth: 0,
      paddingHorizontal: spacing.xs,
      paddingVertical: 10,
    },
    settingsChipActive: {
      backgroundColor: `${colors.cyan}16`,
      borderColor: `${colors.cyan}88`,
    },
    settingsChipText: {
      color: colors.textMuted,
      fontSize: typography.label,
      fontWeight: "800",
    },
    settingsSegmentText: {
      fontSize: typography.tiny,
      fontWeight: "900",
      textAlign: "center",
    },
    settingsChipTextActive: {
      color: colors.text,
    },
    settingsActionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    settingsActionButton: {
      alignItems: "center",
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.xs,
      minHeight: 44,
      paddingHorizontal: spacing.md,
      paddingVertical: 10,
    },
    settingsActionButtonDisabled: {
      opacity: 0.65,
    },
    settingsActionText: {
      fontSize: typography.label,
      fontWeight: "900",
    },
    settingToggleRow: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderBottomColor: colors.border,
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.md,
      minHeight: 60,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
    },
    settingToggleRowDisabled: {
      opacity: 0.72,
    },
    toggleTextWrap: {
      flex: 1,
      gap: 3,
    },
    toggleTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "700",
    },
    toggleDetail: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      lineHeight: 16,
    },
    nativeSwitchWrap: {
      alignItems: "flex-end",
      justifyContent: "center",
      minWidth: 52,
    },
    monitorUsageRow: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing.sm,
      padding: spacing.md,
    },
    monitorUsageHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    monitorUsageTrack: {
      backgroundColor: colors.inset,
      borderRadius: 5,
      height: 10,
      overflow: "hidden",
    },
    monitorUsageFill: {
      borderRadius: 5,
      height: "100%",
      minWidth: 2,
    },
    disconnectButton: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderColor: colors.softRedBorder,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      gap: spacing.md,
      minHeight: 58,
      padding: spacing.md,
    },
    disconnectButtonPressed: {
      backgroundColor: colors.softRed,
    },
    disconnectIcon: {
      alignItems: "center",
      backgroundColor: colors.softRed,
      borderRadius: radius.sm,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    disconnectTextWrap: {
      flex: 1,
      gap: 2,
    },
    disconnectTitle: {
      color: colors.red,
      fontSize: typography.body,
      fontWeight: "900",
    },
    disconnectDetail: {
      color: colors.textMuted,
      fontSize: typography.tiny,
    },
    summaryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    summaryTile: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
      borderWidth: 1,
      flexBasis: "48%",
      flexGrow: 1,
      gap: 3,
      minHeight: 116,
      padding: spacing.md,
    },
    summaryIcon: {
      alignItems: "center",
      borderRadius: radius.sm,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    summaryLabel: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    summaryValue: {
      fontSize: typography.heading,
      fontWeight: "900",
    },
    summaryDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
    },
    subsectionHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    subsectionHeaderTitle: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.sm,
    },
    subsectionTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "900",
    },
    counterText: {
      color: colors.cyan,
      fontSize: typography.heading,
      fontWeight: "900",
    },
    pageDetailText: {
      color: colors.textMuted,
      fontSize: typography.label,
      lineHeight: 18,
    },
    listRow: {
      alignItems: "center",
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: "row",
      gap: spacing.md,
      minHeight: 64,
      paddingTop: spacing.md,
    },
    listIcon: {
      alignItems: "center",
      backgroundColor: colors.surfaceLift,
      borderRadius: radius.md,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    listText: {
      flex: 1,
      gap: 3,
    },
    listTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    sessionTitleRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.xs,
    },
    sessionListTitle: {
      flex: 1,
      lineHeight: 20,
    },
    sessionPinnedDot: {
      alignItems: "center",
      backgroundColor: `${colors.amber}16`,
      borderRadius: 9,
      height: 18,
      justifyContent: "center",
      marginTop: 1,
      width: 18,
    },
    sessionPreview: {
      color: colors.textDim,
      fontSize: typography.tiny,
    },
    listDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
    },
    tasksHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.md,
      paddingHorizontal: spacing.xs,
    },
    tasksHeaderText: {
      flex: 1,
      gap: 2,
    },
    tasksTitle: {
      color: colors.text,
      fontSize: typography.heading,
      fontWeight: "800",
    },
    tasksSubtitle: {
      color: colors.textMuted,
      fontSize: typography.label,
    },
    tasksNewButton: {
      alignItems: "center",
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.xs,
      minHeight: 40,
      paddingHorizontal: spacing.md,
    },
    tasksNewText: {
      fontSize: typography.body,
      fontWeight: "800",
    },
    tasksEmpty: {
      alignItems: "center",
      gap: spacing.sm,
      paddingVertical: spacing.md,
    },
    tasksEmptyIcon: {
      borderRadius: radius.lg,
      height: 52,
      width: 52,
    },
    tasksEmptyTitle: {
      color: colors.text,
      fontSize: typography.heading,
      fontWeight: "800",
    },
    tasksEmptyDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
      paddingHorizontal: spacing.md,
      textAlign: "center",
    },
    tasksEmptyCta: {
      alignItems: "center",
      borderRadius: radius.md,
      flexDirection: "row",
      gap: spacing.sm,
      justifyContent: "center",
      marginTop: spacing.xs,
      minHeight: 48,
      paddingHorizontal: spacing.lg,
    },
    tasksEmptyCtaText: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    emptyState: {
      alignItems: "center",
      borderColor: colors.border,
      borderRadius: radius.lg,
      borderWidth: 1,
      gap: spacing.xs,
      padding: spacing.xl,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: typography.body,
      fontWeight: "800",
    },
    emptyDetail: {
      color: colors.textMuted,
      fontSize: typography.label,
      textAlign: "center",
    },
    tabBar: {
      borderColor: colors.borderStrong,
      borderRadius: MOBILE_NAV_CHROME.outerRadius,
      borderWidth: 1,
      height: MOBILE_NAV_CHROME.height,
      left: MOBILE_MAIN_TAB_CHROME.outerHorizontalPadding,
      overflow: "hidden",
      position: "absolute",
      right: MOBILE_MAIN_TAB_CHROME.outerHorizontalPadding,
    },
    tabBarPanel: {
      flex: 1,
      borderRadius: MOBILE_NAV_CHROME.outerRadius,
      paddingHorizontal: spacing.md,
      paddingVertical: 5,
    },
    tabBarFill: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      gap: spacing.xs,
    },
    tabItem: {
      alignItems: "center",
      borderRadius: radius.sm,
      flex: 1,
      gap: 2,
      height: 48,
      justifyContent: "center",
    },
    tabItemActive: {
      backgroundColor: colors.softCyan,
      borderColor: colors.softCyanBorder,
      borderWidth: 1,
    },
    tabLabel: {
      color: colors.textMuted,
      fontSize: typography.tiny,
      fontWeight: "700",
    },
    tabLabelActive: {
      color: colors.cyan,
    },
  });

export let styles = makeStyles();
subscribeColors(() => {
  styles = makeStyles();
});
