import { StyleSheet } from "react-native";
import { colors, radius, spacing, typography } from "../theme/liquidGlass";

export const botStyles = StyleSheet.create({
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: 140,
    gap: spacing.sm,
  },
  actionRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  primaryAction: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    height: 44,
    borderRadius: radius.md,
    backgroundColor: colors.softCyan,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.softCyanBorder,
  },
  primaryActionText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: "600",
  },
  secondaryAction: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    height: 44,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  secondaryActionText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: "600",
  },
  actionPressed: { opacity: 0.7 },
  actionDisabled: { opacity: 0.4 },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    height: 40,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.inset,
  },
  searchInput: {
    flex: 1,
    color: colors.text,
    fontSize: typography.body,
    paddingVertical: 0,
  },
  hiddenToggle: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.sm,
    backgroundColor: colors.insetStrong,
  },
  hiddenToggleText: {
    color: colors.textMuted,
    fontSize: typography.tiny,
    fontWeight: "600",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.xs,
    marginTop: spacing.xs,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: typography.heading,
    fontWeight: "700",
  },
  sectionCount: {
    color: colors.textDim,
    fontSize: typography.label,
    fontWeight: "600",
  },
  list: {
    borderRadius: radius.lg,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    overflow: "hidden",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  rowPressed: { backgroundColor: colors.inset },
  rowText: { flex: 1, minWidth: 0, gap: 2 },
  rowTitleLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  rowTitle: {
    flexShrink: 1,
    color: colors.text,
    fontSize: typography.body,
    fontWeight: "700",
  },
  rowTime: {
    marginLeft: "auto",
    color: colors.textDim,
    fontSize: typography.tiny,
    fontWeight: "600",
  },
  rowRole: {
    color: colors.textMuted,
    fontSize: typography.label,
  },
  rowPreview: {
    color: colors.textDim,
    fontSize: typography.label,
    lineHeight: 16,
  },
  pinDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.amber,
  },
  presenceDot: {
    position: "absolute",
    right: -2,
    bottom: -2,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.surface,
    backgroundColor: colors.green,
  },
  avatar: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  avatarText: {
    color: "#fff",
    fontWeight: "700",
  },
  roomIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.softCyan,
  },
  footerNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  footerNoteText: {
    flex: 1,
    color: colors.textDim,
    fontSize: typography.tiny,
    lineHeight: 15,
  },
  sheetBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.scrim,
  },
  sheet: {
    maxHeight: "88%",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxl,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    backgroundColor: colors.backgroundLift,
    gap: spacing.sm,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 36,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.borderStrong,
    marginBottom: spacing.xs,
  },
  sheetTitle: {
    color: colors.text,
    fontSize: typography.heading,
    fontWeight: "700",
  },
  sheetDetail: {
    color: colors.textMuted,
    fontSize: typography.label,
    lineHeight: 17,
  },
  fieldLabel: {
    color: colors.textDim,
    fontSize: typography.tiny,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginTop: spacing.xs,
  },
  input: {
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.inset,
    color: colors.text,
    fontSize: typography.body,
  },
  inputMultiline: {
    minHeight: 84,
    textAlignVertical: "top",
  },
  chipRail: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
  },
  chip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chipActive: {
    borderColor: colors.softCyanBorder,
    backgroundColor: colors.softCyan,
  },
  chipText: {
    color: colors.textMuted,
    fontSize: typography.label,
    fontWeight: "600",
  },
  chipTextActive: { color: colors.text },
  selectRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  selectRowActive: {
    borderColor: colors.softCyanBorder,
    backgroundColor: colors.softCyan,
  },
  selectText: { flex: 1, minWidth: 0 },
  selectTitle: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: "600",
  },
  selectDetail: {
    color: colors.textDim,
    fontSize: typography.tiny,
  },
  check: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  checkActive: {
    borderColor: colors.cyan,
    backgroundColor: colors.cyan,
  },
  sheetActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  errorText: {
    color: colors.red,
    fontSize: typography.label,
  },
});
