import {
  Alibaba,
  Amp,
  Anthropic,
  Antigravity,
  Arcee,
  Azure,
  Baidu,
  Bedrock,
  Cerebras,
  Claude,
  Cloudflare,
  Cohere,
  Copilot,
  DeepInfra,
  DeepSeek,
  Devin,
  Doubao,
  ElevenLabs,
  Featherless,
  Fireworks,
  Gemini,
  GithubCopilot,
  Google,
  Grok,
  Groq,
  HuggingFace,
  Hunyuan,
  KiloCode,
  Kimi,
  LmStudio,
  LongCat,
  Meta,
  Minimax,
  Mistral,
  Moonshot,
  NousResearch,
  Novita,
  Nvidia,
  Ollama,
  OpenAI,
  OpenRouter,
  Perplexity,
  Qwen,
  Spark,
  Stepfun,
  Tencent,
  Together,
  Venice,
  Vercel,
  VertexAI,
  Vllm,
  Volcengine,
  Wenxin,
  XAI,
  XiaomiMiMo,
  ZAI,
  type IconType,
} from "@lobehub/icons";

const PROVIDER_ICONS: Record<string, IconType> = {
  openai: OpenAI,
  "openai-codex": OpenAI,
  anthropic: Anthropic,
  claude: Claude,
  anthropic_vertex: Anthropic,
  google: Gemini,
  google_vertex: VertexAI,
  "google-gemini-cli": Gemini,
  xai: XAI,
  grok: Grok,
  "xai-oauth": XAI,
  deepseek: DeepSeek,
  ds4: DeepSeek,
  openrouter: OpenRouter,
  ollama: Ollama,
  "ollama-cloud": Ollama,
  groq: Groq,
  mistral: Mistral,
  together: Together,
  minimax: Minimax,
  "minimax-portal": Minimax,
  moonshot: Moonshot,
  kimi: Kimi,
  "kimi-code": Kimi,
  qwen: Qwen,
  "qwen-portal": Qwen,
  alibaba: Alibaba,
  "alibaba-coding-plan": Alibaba,
  "z.ai": ZAI,
  "z.ai-coding": ZAI,
  zai: ZAI,
  cohere: Cohere,
  perplexity: Perplexity,
  fireworks: Fireworks,
  cerebras: Cerebras,
  novita: Novita,
  huggingface: HuggingFace,
  nvidia: Nvidia,
  deepinfra: DeepInfra,
  featherless: Featherless,
  longcat: LongCat,
  stepfun: Stepfun,
  tencent: Tencent,
  hunyuan: Hunyuan,
  volcengine: Volcengine,
  byteplus: Volcengine,
  doubao: Doubao,
  baidu: Baidu,
  qianfan: Baidu,
  ernie: Baidu,
  wenxin: Wenxin,
  spark: Spark,
  azure: Azure,
  azure_foundry: Azure,
  bedrock: Bedrock,
  github_copilot: GithubCopilot,
  "copilot-proxy": Copilot,
  venice: Venice,
  vllm: Vllm,
  sglang: Vllm,
  nous: NousResearch,
  xiaomi: XiaomiMiMo,
  arcee: Arcee,
  antigravity: Antigravity,
  amp: Amp,
  devin: Devin,
  kilocode: KiloCode,
  lmstudio: LmStudio,
  meta: Meta,
  elevenlabs: ElevenLabs,
  "cloudflare-ai-gateway": Cloudflare,
  "vercel-ai-gateway": Vercel,
};

function normalizeProviderId(id: string | null | undefined): string {
  return (id ?? "").trim().toLowerCase();
}

export interface ProviderIconProps {
  provider?: string | null;
  className?: string;
  size?: number;
}

export function ProviderIcon({ provider, className, size = 20 }: ProviderIconProps) {
  const normalized = normalizeProviderId(provider);
  const Icon = PROVIDER_ICONS[normalized];
  if (!Icon) return null;
  return (
    <Icon className={className} style={{ width: size, height: size }} role="img" aria-hidden />
  );
}

export function hasProviderIcon(provider?: string | null): boolean {
  return normalizeProviderId(provider) in PROVIDER_ICONS;
}
