import { printMobileHelp } from "./cli-mobile";

export function rawHelp(version: string, apiBase: string): void {
  console.log("CYBARA CLI");
  console.log("==========");
  console.log("");
  console.log("Usage: cybara [command]");
  console.log("");
  console.log("Commands:");
  console.log("  (none)      Interactive TUI menu");
  console.log("  start       Launch the gateway in the background (add --foreground to attach)");
  console.log("  chat        Interactive chat with AI");
  console.log("    chat --agent <id> --model <id>     Chat with an agent/model override");
  console.log("    chat --router                      Chat through the model router");
  console.log("  status      Show system status");
  console.log("  health      Alias for status");
  console.log("  backup      Backup and restore durable gateway state");
  console.log("    backup list                         List local backups");
  console.log("    backup create [--label NAME]        Create a backup");
  console.log("    backup restore <id> --yes            Restore and restart the gateway");
  console.log("    backup delete <id> --yes             Delete a backup");
  console.log("  gateway     Gateway lifecycle commands");
  console.log("    gateway status          Show gateway health");
  console.log("    gateway logs [--tail N] Show recent gateway logs");
  console.log("    gateway logs --follow   Follow gateway logs");
  console.log("    gateway restart         Restart the gateway");
  console.log("    gateway start           Start the local gateway (background)");
  console.log("  metrics     Show token usage and metrics");
  console.log("  evals       Replayable agent regression tests");
  console.log("    evals list [--json]                  List golden tests and latest status");
  console.log("    evals save <session-id> [--turn N]   Save a completed turn as a golden");
  console.log("    evals replay <golden-id>             Replay one golden test");
  console.log("    evals run                            Run the full golden suite");
  console.log("    evals export [--format jsonl] [--sanitize] [--output PATH]");
  console.log("    evals import <path>                  Import a replayable suite backup");
  console.log("  doctor      Run environment diagnostics");
  console.log("  update      Download and install the latest CLI release (verifies SHA256)");
  console.log(
    "    update --check     Only report whether a newer release exists (non-zero if stale)"
  );
  console.log("    update --force     Reinstall even when already current / no checksum sidecar");
  console.log("    update --version X Install a specific release");
  console.log("  version     Show the current version");
  console.log("    metrics             Usage summary");
  console.log("    metrics analysis    Advanced token analysis");
  console.log("  agents      List configured agents");
  console.log("  config      Config commands");
  console.log("    config            Show all config");
  console.log("    config get <key>  Get config value");
  console.log("    config set <k> <v> Set config value (for example: theme emerald)");
  console.log(
    "    config set reasoning_effort <minimal|low|medium|high|xhigh|max>  Default reasoning effort"
  );
  console.log("  migrate     Import supported legacy agent data");
  console.log("    migrate sources                         Detect import sources");
  console.log("    migrate --apply --preset full           Apply import");
  console.log("    migrate --migrate-secrets --overwrite   Opt into API key import/conflicts");
  console.log("  provider    Provider management commands");
  console.log("    provider list         List configured providers");
  console.log("    provider available    Show available types");
  console.log("    provider add <type>   Add provider (--name, --key, --token, --default)");
  console.log("    provider update <id>  Update provider");
  console.log("    provider delete <id>  Delete provider");
  console.log("    provider models <id>  List provider models");
  console.log("    provider discover     Discover Ollama models");
  console.log("  models      Provider model discovery aliases");
  console.log("    models                 List configured providers");
  console.log("    models available       Show available provider types");
  console.log("    models <provider-id>   List models for a configured provider");
  console.log("  acp         Run an ACP v1 server over stdio for compatible clients");
  console.log("    acp [--agent <id>]    Serve the default or selected agent");
  console.log("  tasks       List scheduled tasks");
  console.log("  skills      List installed skills");
  console.log("  plugin      Plugin management commands");
  console.log("    plugin list                List installed plugins");
  console.log("    plugin validate <path>     Validate a plugin manifest and dirs");
  console.log("    plugin install <path>      Install a local plugin");
  console.log("    plugin remove <plugin-id>  Remove an installed local plugin");
  console.log("  sessions    List chat sessions");
  console.log("  memory      Memory commands");
  console.log("    memory         List recent memories");
  console.log("    memory <query> Search memories");
  console.log("  artifacts   List persistent session deliverables [--json]");
  console.log("  journey     Show learned skills and memory activity [--json]");
  console.log("  logs        Show recent logs");
  console.log("    logs --tail N          Show N recent logs");
  console.log("    logs --follow          Follow logs until interrupted");
  console.log("  subagent    Subagent commands");
  console.log("    subagent list       List subagents");
  console.log("    subagent spawn [--agent <id>] [--model <id>] [--workspace <dir>] <task>");
  console.log("    subagent kill <id>  Kill subagent");
  console.log("  loop        Autonomous agent loop commands");
  console.log("    loop list [--agent <id>]              List loop runs");
  console.log("    loop start <agent-id> <objective>     Start loop");
  console.log("      [--max-iterations N] [--max-duration SEC] [--model ID] [--no-tools]");
  console.log("    loop show <run-id>                    Show loop details");
  console.log("    loop cancel <run-id>                  Cancel a running loop");
  console.log("  browser     Browser commands");
  console.log("    browser            Show browser status");
  console.log("    browser tabs       List open browser tabs");
  console.log("  channels    List configured channels");
  console.log("  connectors  Account connector commands");
  console.log("    connectors list");
  console.log("    connectors configure <connector-id> --client-id <id>");
  console.log("    connectors connect|disconnect|setup <connector-id>");
  console.log("  mobile      Mobile companion commands");
  printMobileHelp("    ");
  console.log("  devices     Alias for mobile device management");
  console.log("  wallet      Wallet management commands");
  console.log("    wallet status                     Show wallet status and RPC settings");
  console.log("    wallet create --password <p>      Create 24-word wallet");
  console.log('    wallet import --password <p> --mnemonic "..."   Import wallet');
  console.log("    wallet unlock --password <p>      Unlock wallet");
  console.log("    wallet reveal-seed --password <p> --confirm REVEAL");
  console.log("    wallet lock                       Lock wallet");
  console.log("    wallet accounts [--chains c] [--count n] [--start n]");
  console.log("    wallet balances [--chains c] [--count n] [--start n]");
  console.log("    wallet tokens <eth|sol> [--index n] [--include-zero]");
  console.log("    wallet token-tx <eth|sol> [--index n] [--limit n] [--token addr]");
  console.log("    wallet receive <chain> [--index n]");
  console.log("    wallet tx <chain> [--index n] [--limit n]");
  console.log("    wallet send <chain> --to <addr> --amount <value>");
  console.log("    wallet send-token <eth|sol> --token <addr|mint> --to <addr> --amount <value>");
  console.log("    wallet swap-eth-uniswap --token <symbol|addr> --percent 50 [--execute]");
  console.log("    wallet price [BTC|BTC/USD|<SOL_MINT>] [--source auto|chainlink|pyth|jupiter]");
  console.log("    wallet swap [<TOKEN>] [--venue uniswap_v3|uniswap_v2|jupiter] [--execute]");
  console.log("    wallet endpoints");
  console.log("    wallet dapps");
  console.log("    wallet rpc-call <eth|sol> --method <rpc_method> [--params '[...]']");
  console.log("    wallet dapp --adapter <adapter> --json '{...}'");
  console.log("    wallet x402 --url <https_url> [--method GET|POST] [--dry-run]");
  console.log("    wallet swap-quote ...        # legacy alias for wallet swap (quote)");
  console.log("    wallet swap-execute ...      # legacy alias for wallet swap --execute");
  console.log(
    "    wallet contract-call --contract <addr> (--abi '<json_or_sig>' | --signature '<name(types)>') [--method <name>]"
  );
  console.log("    wallet sol-instruction --program <id> (--keys '[...]' | --accounts '[...]')");
  console.log("    wallet agent-access <on|off>");
  console.log("    wallet agent-policy [show]");
  console.log("    wallet agent-policy set --json '{...}'");
  console.log("    wallet rpc [show]");
  console.log("    wallet rpc status");
  console.log("    wallet rpc set [--eth URL] [--sol URL] [--btc URL]");
  console.log("  pair        Channel pairing commands");
  console.log("    pair           List pending pairings");
  console.log("    pair <CODE>    Approve a pairing code");
  console.log("    pair reject    Reject a pairing code");
  console.log("    pair policy    Set DM policy for a channel");
  console.log("  pairing     Alias for pair");
  console.log("  mcp         MCP server commands");
  console.log("    mcp list     List installed MCP servers");
  console.log("    mcp add      Add a remote HTTPS server");
  console.log("    mcp search   Search MCP registry");
  console.log("    mcp install  Install MCP server");
  console.log("    mcp popular  Show popular servers");
  console.log("  lsp         Language Server commands");
  console.log("    lsp list       Show language server status");
  console.log("    lsp install    Install language server");
  console.log("    lsp uninstall  Uninstall language server");
  console.log("  wizard      Run setup wizard (first-time configuration)");
  console.log("  configure   Alias for setup wizard");
  console.log("  onboard     Alias for setup wizard");
  console.log("  completion  Print shell completion script (zsh or bash)");
  console.log("  help        Show this help");
  console.log("");
  console.log("Common flags:");
  console.log("  -h, --help        Show help (works after any command)");
  console.log("  -v, --version     Print version");
  console.log("  -f, --foreground  Run 'start' attached to this terminal");
  console.log("  -c, --check       'update' — check only, don't install");
  console.log("  -y, --yes         Skip confirmation prompts");
  console.log("  -j, --json        JSON output where supported");
  console.log("  -n/-k/-t/-d/-o    provider add: name/key/token/default/oauth");
  console.log("");
  console.log(`Version: ${version}`);
  console.log(`Environment: CYBARA_API=${apiBase}`);
}
