import puppeteer, { type Browser, type Page } from "puppeteer-core";
import { spawn, type ChildProcess } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { chromium } from "playwright";

const CDP_PORT_RANGE_START = 18800;
const CDP_PORT_RANGE_END = 18900; // 100 profiles max

export interface BrowserProfile {
  name: string;
  cdpPort: number;
  cdpUrl: string;
  color: string;
  userDataDir: string;
  running: boolean;
  lastTargetId: string | null;
}

export interface BrowserProfileConfig {
  name: string;
  cdpPort?: number;
  color?: string;
  headless?: boolean;
  executablePath?: string;
  userDataDir?: string;
  attachOnly?: boolean;
}

const browsers = new Map<string, { process: ChildProcess; browser: Browser }>();
const pages = new Map<string, Page>();
const profiles = new Map<string, BrowserProfile>();
const usedPorts = new Set<number>();

function getConfigDir(): string {
  const configDir = process.env.CONFIG_DIR || path.join(os.homedir(), ".cybara");
  return path.join(configDir, "browser");
}

export function resolveUserDataDir(profileName: string): string {
  const configDir = getConfigDir();
  return path.join(configDir, profileName, "user-data");
}

function findAvailablePort(): number {
  for (let port = CDP_PORT_RANGE_START; port < CDP_PORT_RANGE_END; port++) {
    if (!usedPorts.has(port)) {
      return port;
    }
  }
  throw new Error("No available CDP ports");
}

export async function createProfile(config: BrowserProfileConfig): Promise<BrowserProfile> {
  const name = config.name;
  const cdpPort = config.cdpPort || findAvailablePort();
  const color = config.color || "#F4B400"; // Cybara gold (like Cybara yellow)
  const userDataDir = config.userDataDir || resolveUserDataDir(name);

  if (!fs.existsSync(userDataDir)) {
    fs.mkdirSync(userDataDir, { recursive: true });
  }

  const defaultDir = path.join(userDataDir, "Default");
  if (!fs.existsSync(defaultDir)) {
    fs.mkdirSync(defaultDir, { recursive: true });
  }

  const prefsPath = path.join(defaultDir, "Preferences");
  if (!fs.existsSync(prefsPath)) {
    const prefs = {
      profile: {
        name: `Cybara Agent - ${name}`,
        avatar_index: 26, // Robot avatar
        managed_user_id: "",
        is_using_default_name: false,
        is_using_default_avatar: false,
      },
      autogenerated_theme_color: 16041984, // #F4B400 as decimal (244*65536 + 180*256 + 0)
      browser: {
        theme: {
          follows_system_colors: false,
          color_variant: 0,
          user_color: 16041984, // Gold #F4B400
        },
      },
      ntp: {
        custom_background_dict: {},
      },
    };
    fs.writeFileSync(prefsPath, JSON.stringify(prefs, null, 2));
    console.log(`[Browser] Created profile with Cybara gold theme: ${name}`);
  }

  const profile: BrowserProfile = {
    name,
    cdpPort,
    cdpUrl: `http://127.0.0.1:${cdpPort}`,
    color,
    userDataDir,
    running: false,
    lastTargetId: null,
  };

  profiles.set(name, profile);
  usedPorts.add(cdpPort);

  return profile;
}

export function getProfile(name: string): BrowserProfile | undefined {
  return profiles.get(name);
}

export function listProfiles(): BrowserProfile[] {
  return Array.from(profiles.values());
}

export async function deleteProfile(name: string): Promise<void> {
  const profile = profiles.get(name);
  if (!profile) return;

  if (profile.running) {
    await stopBrowser(name);
  }

  profiles.delete(name);
  usedPorts.delete(profile.cdpPort);
}

async function findChromeExecutable(): Promise<string | null> {
  const platform = process.platform;

  let chromePaths: (string | undefined)[] = [];

  if (platform === "darwin") {
    chromePaths = [
      "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      "/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary",
      "/Applications/Chromium.app/Contents/MacOS/Chromium",
      "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
      "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
      os.homedir() + "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ];
  } else if (platform === "win32") {
    const programFiles = process.env["ProgramFiles"] || "C:\\Program Files";
    const programFilesX86 = process.env["ProgramFiles(x86)"] || "C:\\Program Files (x86)";
    const localAppData = process.env["LOCALAPPDATA"] || "";

    chromePaths = [
      `${programFiles}\\Google\\Chrome\\Application\\chrome.exe`,
      `${programFilesX86}\\Google\\Chrome\\Application\\chrome.exe`,
      `${localAppData}\\Google\\Chrome\\Application\\chrome.exe`,
      `${programFiles}\\Microsoft\\Edge\\Application\\msedge.exe`,
      `${programFilesX86}\\Microsoft\\Edge\\Application\\msedge.exe`,
      `${programFiles}\\BraveSoftware\\Brave-Browser\\Application\\brave.exe`,
      `${localAppData}\\BraveSoftware\\Brave-Browser\\Application\\brave.exe`,
      `${programFiles}\\Chromium\\Application\\chrome.exe`,
    ];
  } else {
    chromePaths = [
      "/usr/bin/google-chrome",
      "/usr/bin/google-chrome-stable",
      "/usr/bin/chromium",
      "/usr/bin/chromium-browser",
      "/snap/bin/chromium",
      "/usr/bin/brave-browser",
      "/usr/bin/microsoft-edge",
      "/usr/bin/microsoft-edge-stable",
    ];
  }

  if (process.env.CHROME_PATH) {
    chromePaths.unshift(process.env.CHROME_PATH);
  }

  for (const chromePath of chromePaths) {
    if (chromePath && fs.existsSync(chromePath)) {
      console.log(`[Browser] Using system browser: ${chromePath}`);
      return chromePath;
    }
  }

  try {
    const playwrightPath = chromium.executablePath();
    console.log(`[Browser] Using Playwright Chromium: ${playwrightPath}`);
    return playwrightPath;
  } catch {
    console.warn(
      "[Browser] No Chrome/Chromium found. Install a browser or run: bunx playwright install chromium"
    );
    return null;
  }
}

export async function startBrowser(profileName: string): Promise<Browser> {
  let profile = profiles.get(profileName);
  if (!profile) {
    profile = await createProfile({ name: profileName });
  }

  if (browsers.has(profileName)) {
    return browsers.get(profileName)!.browser;
  }

  const executablePath = await findChromeExecutable();
  if (!executablePath) {
    throw new Error(
      "Chrome/Chromium not found. Install Playwright browsers: bunx playwright install chromium"
    );
  }

  const chromeArgs = [
    `--remote-debugging-port=${profile.cdpPort}`,
    `--remote-debugging-address=127.0.0.1`,
    `--user-data-dir=${profile.userDataDir}`,
    "--no-first-run",
    "--no-default-browser-check",
    "--disable-default-apps",
    "--disable-popup-blocking",
    "--disable-translate",
    "--disable-background-networking",
    "--disable-sync",
    "--disable-features=TranslateUI",
    "--window-size=1920,1080",
    "--window-position=0,0",
  ];

  const platform = process.platform;
  if (platform === "linux") {
    if (process.env.CI || process.env.DOCKER) {
      chromeArgs.push("--no-sandbox");
    }
    chromeArgs.push("--disable-dev-shm-usage");
  }

  return new Promise((resolve, reject) => {
    const proc = spawn(executablePath, chromeArgs, {
      stdio: ["ignore", "pipe", "pipe"],
      detached: false,
    });

    proc.on("error", (err) => {
      reject(new Error(`Failed to start Chrome: ${err.message}`));
    });

    const cdpUrl = profile!.cdpUrl;
    const maxAttempts = 30; // 30 * 500ms = 15 seconds max
    let attempts = 0;
    let connected = false; // Flag to prevent multiple connections

    const checkCDP = async () => {
      if (connected) return; // Already connected, stop polling

      attempts++;
      try {
        const response = await fetch(`${cdpUrl}/json/version`, {
          signal: AbortSignal.timeout(1000),
        });
        if (response.ok && !connected) {
          const versionData = (await response.json()) as { webSocketDebuggerUrl?: string };
          const wsUrl = versionData.webSocketDebuggerUrl;

          if (!wsUrl) {
            console.log(`[Browser] CDP responded but no WebSocket URL, retrying...`);
            return; // Retry
          }

          connected = true; // Mark as connected immediately

          console.log(`[Browser] CDP ready after ${attempts * 500}ms, connecting via ${wsUrl}...`);
          const browser = await puppeteer.connect({
            browserWSEndpoint: wsUrl,
            defaultViewport: null, // Use Chrome window's natural viewport size
          });

          browsers.set(profileName, { process: proc, browser });
          profile!.running = true;

          console.log(`[Browser] Connected to Chrome via CDP WebSocket (Puppeteer)`);
          resolve(browser);
          return;
        }
      } catch {
        void 0;
      }

      if (connected) return; // Check again in case connection happened

      if (attempts >= maxAttempts) {
        proc.kill();
        reject(new Error(`Chrome CDP not available at ${cdpUrl} after ${maxAttempts * 500}ms`));
        return;
      }

      setTimeout(checkCDP, 500);
    };

    setTimeout(checkCDP, 500);
  });
}

export async function stopBrowser(profileName: string): Promise<void> {
  const instance = browsers.get(profileName);
  if (!instance) return;

  for (const [pageId, page] of pages) {
    if (pageId.startsWith(profileName)) {
      await page.close().catch(() => {});
      pages.delete(pageId);
    }
  }

  await instance.browser.close();

  instance.process.kill();

  browsers.delete(profileName);

  const profile = profiles.get(profileName);
  if (profile) {
    profile.running = false;
    profile.lastTargetId = null;
  }
}

export async function getBrowser(profileName: string): Promise<Browser> {
  const existing = browsers.get(profileName);
  if (existing) return existing.browser;
  return await startBrowser(profileName);
}

export async function createPage(profileName: string, url?: string): Promise<Page> {
  const browser = await getBrowser(profileName);

  const existingPages = await browser.pages();
  let page: Page;

  if (existingPages.length > 0 && !existingPages[0].url().includes("about:blank") === false) {
    page = existingPages[0];
    console.log(`[Browser] Using existing page for profile: ${profileName}`);
  } else {
    page = await browser.newPage();
    console.log(`[Browser] Created new page for profile: ${profileName}`);
  }

  const pageId = `${profileName}-${Date.now()}`;
  pages.set(pageId, page);

  page.on("close", () => {
    pages.delete(pageId);
  });

  const targetUrl = url?.trim() || "";
  if (targetUrl && targetUrl !== "about:blank") {
    console.log(`[Browser] Navigating to ${targetUrl}...`);
    try {
      await page.goto(targetUrl, { timeout: 30000, waitUntil: "domcontentloaded" });
      console.log(`[Browser] Successfully navigated to ${targetUrl}`);
    } catch (err) {
      console.log(`[Browser] Navigation error (page still created): ${(err as Error).message}`);
    }
  }

  const profile = profiles.get(profileName);
  if (profile) {
    profile.lastTargetId = pageId;
  }

  return page;
}

export function getPage(profileName: string, pageId: string): Page | undefined {
  return pages.get(`${profileName}-${pageId}`) || pages.get(pageId);
}

export async function getActivePage(profileName: string): Promise<Page> {
  const instance = browsers.get(profileName);

  if (instance) {
    const browserPages = await instance.browser.pages();
    if (browserPages.length > 0) {
      return browserPages[browserPages.length - 1];
    }
  }

  return await createPage(profileName);
}

export async function getProfilePages(
  profileName: string
): Promise<Array<{ id: string; url: string; title: string }>> {
  const entries = Array.from(pages.entries()).filter(([id]) => id.startsWith(profileName));

  const result: Array<{ id: string; url: string; title: string }> = [];
  for (const [id, page] of entries) {
    result.push({
      id: id.replace(`${profileName}-`, ""),
      url: page.url(),
      title: await page.title(),
    });
  }
  return result;
}

export async function closePage(profileName: string, pageId: string): Promise<boolean> {
  const fullId = `${profileName}-${pageId}`;
  const page = pages.get(fullId) || pages.get(pageId);
  if (!page) return false;

  await page.close();
  pages.delete(fullId);
  pages.delete(pageId);
  return true;
}

export async function closeAllPages(profileName: string): Promise<void> {
  for (const [id, page] of pages.entries()) {
    if (id.startsWith(profileName)) {
      await page.close().catch(() => {});
      pages.delete(id);
    }
  }
}

export async function getStatus(): Promise<{
  running: boolean;
  profiles: BrowserProfile[];
  totalPages: number;
}> {
  return {
    running: browsers.size > 0,
    profiles: listProfiles(),
    totalPages: pages.size,
  };
}

export async function shutdownAll(): Promise<void> {
  for (const [name] of browsers) {
    await stopBrowser(name);
  }
}

export function getPagesMap(): Map<string, Page> {
  return pages;
}

export function getBrowsersMap(): Map<string, { process: ChildProcess; browser: Browser }> {
  return browsers;
}
